### ISSUE TITLE
Malformed variables caused by automated simplification of expressions

### ISSUE THREAD

**Issue by Jesright73** [UnderminersTeam/UndertaleModTool#1032]
### Describe the bug

Parentheses removal caused by the expression simplification procedure performed by UMT during code entry edit/compiling can lead to malformed variables, especially when expressions include **compare** operators. 

###  Original code from AM2R before editing:
![image](https://user-images.githubusercontent.com/79653967/177022741-f8a2a480-33d4-46d7-8b3c-1b0e2c45b1b3.png)

### Code entry after changing the `1` to a `0` in the first line:
![image](https://user-images.githubusercontent.com/79653967/177022807-2637f926-8a5a-4ae0-82af-0149027b3fcb.png)

### Reproducing steps

1. Edit a code entry containing an expression with a compare operator followed by a math operation.
_example_ `(image_angle + ((image_xscale == -1) * 180))`
2. Edit and compile the code entry
3. Observe the parentheses are removed from around the compare operation
_result_ `(image_angle + (image_xscale == -1 * 180))`
No errors when effected code is run.
4. Edit and compile the code entry again.
5. Notice the compare operator's number is now combined with the adjacent math operation. 
_result_ `(image_angle + image_xscale == -180)`
Attempting to run the effected code will now result in a "Malformed Variable" error.

### Setup Details

**UndertaleModTool** v:85430c5 (master)
**OS:** Windows 10 21H1
**Game:** [Another Metroid 2 Remake](https://github.com/AM2R-Community-Developers/AM2RLauncher/releases)
**Code entry from AM2R used in example:** gml_Object_oSpaceJumpTrail_Draw_0

**Comment by themabus** [comment]
I seem to have encountered the same problem but with decompiler not compiler, i.e. presented Decompiled code is non working because of missing brackets.
It appears to have been parsed correctly in v0.3.0 and was already broken in v0.3.5.8
I didn't check versions in between.
This is still present in '674c5d8' bleeding edge.
