### ISSUE TITLE
UMT crashes ocasionally: System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Jesright73** [UnderminersTeam/UndertaleModTool#1068]
### Describe the bug

UMT occasionally crashes. Has happened twice: first time crashed when moving mouse to the menu bar; Second time occurred when right-clicking an asset in the room list.
[crash.txt](https://github.com/krzys-h/UndertaleModTool/files/9214374/crash.txt)

### Reproducing steps

Unable to reliably replicate. 

### Setup Details

**UMT version:** Bleeding Edge 674c5d8 
**OS:** Windows 10 21H1
**Game:** AM2R

**Comment by Miepee** [comment]
@Jesright73 are you still able to replicate this issue?

**Comment by Jesright73** [comment]
Haven't encountered this since i began using `isSingleFile_false` releases. i will test the most recent `isSingleFile_true` release for this issue.

**Comment by Jacky720** [comment]
@Jesright73 Have you performed that test, and did it work?

**Comment by Jesright73** [comment]
Haven't experienced the error yet, though i can't say i've used the SingleFile package long enough to tell.

**Comment by Miepee** [comment]
Then let's close the issue. If you do encounter it again, just comment or reopen it.

**Comment by Jesright73** [comment]
The error has occurred again, when clicking to open the file menu. Same crash message as before. [crash.txt](https://github.com/UnderminersTeam/UndertaleModTool/files/15501071/crash.txt)
UMT version: Bleeding Edge "isSingleFile-true" (last updated May 2 2024)

i will switch back to isSingleFile-false, as i've never experienced the error with that build type.

This issue is not isolated to UndertaleModTool. The same error was reported on the wpf repo by others.
https://github.com/dotnet/wpf/issues/7751

**Comment by Miepee** [comment]
opened the issue before reading the comment, whoops.
Since it's an upstream issue, I will close this. Does seem so to be really annoying tho, especially with this unable to be reliably replicated :/
