### ISSUE TITLE
loading 2022.3 game error

### ISSUE THREAD

**Issue by Mantou1233** [UnderminersTeam/UndertaleModTool#1074]
### Describe the bug

UTMT cannot load a game (gms 2022.3), having a error

### Reproducing steps

Open https://gamejolt.com/games/Xuwugames_PVZ_Void/714049 and it errors
![image](https://user-images.githubusercontent.com/74487898/184494922-87f62fe9-e46d-450d-9b83-2ee8cedf1663.png)
![image](https://user-images.githubusercontent.com/74487898/184494924-ea771f5c-d425-41f9-a858-25e6d41cf421.png)

### Setup Details

UTMT latest nightly
windows
https://gamejolt.com/games/Xuwugames_PVZ_Void/714049

**Comment by Jacky720** [comment]
Has this been resolved?

**Comment by Jacky720** [comment]
Game opens on current bleeding edge.
