### ISSUE TITLE
Undertale files won't open

### ISSUE THREAD

**Issue by TrueGodOfHyperdeath** [UnderminersTeam/UndertaleModTool#1075]
### Describe the bug

Hello. When trying to open the data.win file from the Undertale game, this error pops up:

![image](https://user-images.githubusercontent.com/96071214/186772512-b58da190-604b-4e79-8587-083965b6c899.png)

### Reproducing steps

Open data.win file via UndertaleModTool

### Setup Details

1.  UndertaleModTool_NSF_v0.4.0.4 or UndertaleModTool_v0.4.0.4
2. Windows 7
3. Undertale v1.08c

**Comment by Jacky720** [comment]
What's 1.08c? Like, 1.08 (C), the copyright info? Or is there some mod from the base game?

**Comment by Dobby233Liu** [comment]
> What's 1.08c? Like, 1.08 (C), the copyright info?

AFAIK some pirated versions label 1.08 like that.

**Comment by Jacky720** [comment]
This issue has gone stale and probably regards piracy. (Also, #855). Closing.
