### ISSUE TITLE
bleeding edge wont work 

### ISSUE THREAD

**Issue by kkmfd-Offical** [UnderminersTeam/UndertaleModTool#1086]
### Describe the bug

it leads to the command console and gives an error

### Reproducing steps

Open The File
Open The App
GIVES THE FRICKEN ERROR

### Setup Details

Bleeding edge

Macos Montery

**Comment by Jacky720** [comment]
1. What error?
2. Did you download the CLI version? You're supposed to get a GUI version (it doesn't matter single file or not).

**Comment by Miepee** [comment]
macOS doesn't have a GUI version.
But yeah, more info is needed. Did you download the CLI version? If yes, how did you open it?

**Comment by Miepee** [comment]
No info provided in 1.5 years. Closing as stale.
