### ISSUE TITLE
texture page error while loading the data.win

### ISSUE THREAD

**Issue by donsoyer** [UnderminersTeam/UndertaleModTool#1111]
### Describe the bug
![image](https://user-images.githubusercontent.com/96090807/200478327-d26b4acc-619b-42b2-b889-80ffe0aca3e4.png)

![image](https://user-images.githubusercontent.com/96090807/200477795-71014aea-b1f0-42b5-a8be-12c107e36f69.png)

### Reproducing steps

See texture page error while loading the data.win

### Setup Details

game made by new version of GMS2 with latest update, undertaleModTool used is also latest, Win10.

**Comment by Miepee** [comment]
"Latest update" is not specific.
please specify the GMS2 and UndertaleModTool version you used.

**Comment by donsoyer** [comment]
GMS2: ![image](https://user-images.githubusercontent.com/96090807/200743652-6d6b798e-88b0-4d90-876f-eb96ff95c304.png)
Undertale 
![image](https://user-images.githubusercontent.com/96090807/200743749-6ea569bc-e7ba-4125-96b9-34a293f0319c.png)

**Comment by Jacky720** [comment]
Has this been fixed?

**Comment by donsoyer** [comment]
no.

**Comment by VladiStep** [comment]
Could you say the name of the game (or share "data.win" file if the game was created by you) ?

**Comment by Miepee** [comment]
@donsoyer can you pleas share the name of the game,  or if the game was made by you the data.win?

**Comment by Miepee** [comment]
Gonna close this due to lack of info
feel free to reopen this if you can provide more info
