### ISSUE TITLE
HIGH RISK OF DATA LOSS

### ISSUE THREAD

**Issue by siqian29** [UnderminersTeam/UndertaleModTool#1126]
### Describe the bug

open data.win failed
![微信图片_20221121105044](https://user-images.githubusercontent.com/118703053/202952955-cb36f61e-0c27-4c40-a700-fd152f1a7e9e.png)
![微信图片_20221121105035](https://user-images.githubusercontent.com/118703053/202952991-3475f211-43ea-4785-89dd-0cf3633eb15c.png)

### Reproducing steps

当打开data.win时候报错

### Setup Details

1. windows10操作系统
2. GUI-windows-latest-isBundled-true-isSingleFile-false

**Comment by Jacky720** [comment]
What game is this?

**Comment by ekinciufukemre** [comment]
Hisptale https://gamejolt.com/games/Hispatale/729664

**Comment by VladiStep** [comment]
The current version of this game (1.5.0) successfully loads on the current bleeding edge.
Where is it possible to download the version that you've tried to load?

**Comment by Miepee** [comment]
marking as closed due to above
