### ISSUE TITLE
File name length crash on Mac and Linux

### ISSUE THREAD

**Issue by aiden3c** [UnderminersTeam/UndertaleModTool#1182]
### Describe the bug

When using UMT to get code from Pizza Tower, at least one of the files has a name longer than 255 characters. On Mac and Linux this means the file can't save, and the tool crashes from a System.IO exception.

### Reproducing steps

1. Use the mod tool CLI on Linux (or Mac)
2. Extract the code from Pizza Tower's data.win

### Setup Details

Using bleeding edge

Tested on Manjaro, but it's a limitation of a lot of Unix filesystems.

**Comment by VladiStep** [comment]
There's the "ExportAllCode2_3.csx", try it.
Though it is much slower than the regular version, because it doesn't use parallel processing.

**Comment by Jacky720** [comment]
Vlad's solution is valid and this issue has been inactive for a year, closing. ExportAllCode2_3 should probably have a synchronous version but that is a separate issue.
