### ISSUE TITLE
Sounds not in the sounds section.

### ISSUE THREAD

**Issue by KritzTF2** [UnderminersTeam/UndertaleModTool#1184]
### Describe the bug

Whenever I load up a GM2 game (That isn't Undertale) I can NEVER see the sounds

### Reproducing steps

1. open the application
2. load the data file
3. see if the sounds section can be opened, and see it can't be

### Setup Details

I've used the latest version

**Comment by Grossley** [comment]
Not enough information provided. Please provide game name, link to game, specific version ("latest version" is not good enough).

**Comment by Jacky720** [comment]
This issue has been inactive for a year without enough details to reproduce (and many GMS2 games definitely have sounds the tool can load). Closing.
