### ISSUE TITLE
Undertale Won't Open

### ISSUE THREAD

**Issue by dinoman009** [UnderminersTeam/UndertaleModTool#1189]
### Describe the bug

Other than some Strings, I haven't changed any code, and now Undertale won't open. Whenever I try to run a Temp file, or even open the actual game, it pauses for a few seconds, then crashes. It's never done this before. I didn't see a "help" section, so I'm just putting this here.

### Reproducing steps

All I've done was change the intro text and intro sprites. Then, I accidentally changed the Frisk Down Sprite to something way to large. Now, I can't change it back to the original sprite, and the game won't open.

### Setup Details

I have no clue what to put here.

**Comment by Jacky720** [comment]
Sounds like your new sprite may have had mask or padding issues. On the off-chance that you're still having this problem (sorry for the delay), I would recommend seeking help in the Underminers Discord. The ImportGraphics script can reliably add new sprites and possibly even fix this one.

**Comment by Miepee** [comment]
@dinoman009 do you still have the issue?

**Comment by Miepee** [comment]
I'm going to close the issue due to being inactionable.
Please reopen it should you still have the issue.
