### ISSUE TITLE
Functions cause compiling issues with code

### ISSUE THREAD

**Issue by scyrulean** [UnderminersTeam/UndertaleModTool#1192]
### Describe the bug

Trying to mod pizza tower as people do, whilst I'm restoring something, every time a function is defined, it causes compiling issues. 

Error listed below:

> /* EXCEPTION!
>
>   System.InvalidOperationException: Sequence contains no matching element
>   at System.Linq.ThrowHelper.ThrowNoMatchException()
>   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Dictionary`2 blocks, Block block, >List`1 tempvars, Stack`1 workQueue) in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler>\Decompiler.cs:line 2358
>   at UndertaleModLib.Decompiler.Decompiler.DecompileFromBlock(DecompileContext context, Dictionary`2 blocks, Block block) >in D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 2614
>   at UndertaleModLib.Decompiler.Decompiler.Decompile(UndertaleCode code, GlobalDecompileContext globalContext) in >D:\a\UndertaleModTool\UndertaleModTool\UndertaleModLib\Decompiler\Decompiler.cs:line 3770
>   at UndertaleModTool.UndertaleCodeEditor.<>c__DisplayClass36_0.<DecompileCode>b__1() in D:\a\UndertaleModTool>\UndertaleModTool\UndertaleModTool\Editors\UndertaleCodeEditor.xaml.cs:line 530
>*/

Is there any way to solve this? Any things that I'm doing wrong? Please let me know, I'm going fucking insane.

### Reproducing steps

1.Open the Pizza Tower data.win
2. Search for a script that has functions, In this case gml_Object_obj_mrstickboss_Create_0.
3. Modify some part of the script
4. Error.

### Setup Details

UTModTool Version 0.5.0.0
OS: Windows 10
Game: Pizza Tower running GM Version 2022.9

**Comment by Jacky720** [comment]
We determined this error is because scripts with multiple functions need an offset for each function. This offset is stored in a separate "anonymous script entry" and the UTMT compiler does not currently update it. It applies to any GameMaker game newer than GMS2.3.

**Comment by scyrulean** [comment]
So I need to update the anonymous script entry manually, or is there nothing I can do? Thanks for the answer btw

**Comment by Jacky720** [comment]
Manually would work in theory. Each instruction in assembly counts as four bytes, as far as the offset is concerned. If you compare the before and after of the disassembly, you'll see most of the lines shift around while the "> gml_Script_etc" line stays put. The position of that line is determined by the offset.

Other workarounds include just editing in disassembly, possibly using an object instead, or similar.
