### ISSUE TITLE
Opens better Data.win Pizza Tower file, than Undertale

### ISSUE THREAD

**Issue by CMD28** [UnderminersTeam/UndertaleModTool#1193]
### Describe the bug

When trying to run data.win from Undertale, Undertale Mod Tool is crashing. At the same time, the data.win file of Pizza Tower opens without any problems, although the tool was made for Undertale. In addition, a bad decompiler, when you try to save the code of one script in the code input field through #, a compilation error appears.

### Reproducing steps

1. Open Data.Win of Undertale
2. Appears errors of corrupted files "Reading misaligned at, realigning back to HIGH RISK OF DATA LOSS!" 
3. UndertaleModTool crashing, i tried different versions of Undertale but error the same.

### Setup Details

1. UndertaleModTool Bleeding Edge Bundled True Single file True
2. Windows 7 Service Pack 1
3. Undertale 1.08(mostly)

**Comment by Jacky720** [comment]
I'm not sure what the error regarding # is, but the tool definitely works for Undertale. Will close shortly unless you can reproduce these issues on current bleeding edge.

**Comment by Miepee** [comment]
The fact that it says `Undertale 1.08(mostly)` makes me wonder whether it's related to the 1.08C version from that other issue.

**Comment by Miepee** [comment]
Closing since
1) issue isnt actionable
2) win7 isnt supported
3) likely to be using some pirated version of undertale
