### ISSUE TITLE
the images cut

### ISSUE THREAD

**Issue by TomateCardozo** [UnderminersTeam/UndertaleModTool#1235]
### Describe the bug

my problem is the next: when i export an image of onaf 2 or 3, then i changed and when im back to import it, the image cuts in the app and in the game because its to big and in the game looks cutted, i was thinking that its a problem of my laptop, but is not, its of the app, so pls fix it because i want to make a mod :(

### Reproducing steps

![bandicam 2023-02-24 17-07-32-988](https://user-images.githubusercontent.com/108767738/227652462-f29ecceb-5c26-4671-985f-95f7a5940223.jpg)
![bandicam 2023-02-24 17-07-40-297](https://user-images.githubusercontent.com/108767738/227652464-a3d73895-2d9c-4d2a-87b4-de9d2b96086f.jpg)

### Setup Details

its in the lastest version: the 5.0.0
and it happens in some laptops and pc's

**Comment by Jacky720** [comment]
Hmm. Usually, importing a sprite of a different size would result in it squishing back into the original size and becoming a blurry mess in the process. Here, it just seems like the Texture Page Item has the wrong coordinates set.

Have you tried ImportGraphics.csx, under Repacker Scripts? Normally it handles this stuff automatically. For a background, put it in a folder called "Backgrounds", naming the image <whatevername>; for a sprite, put it in a folder named "Sprites", naming the image <whatevername>_0.

**Comment by TomateCardozo** [comment]
well, the size of the image i dont change it, the only thing i change its the texture, not the size, but im going to try

**Comment by TomateCardozo** [comment]
can u explain me better? or u are bussy? because i dont know what are or where are that folders u name

**Comment by TomateCardozo** [comment]
but thanks for the help

**Comment by TomateCardozo** [comment]
here i have the csx u said:
![bandicam 2023-03-24 21-12-55-960](https://user-images.githubusercontent.com/108767738/227665721-dd461cd6-bb5e-472b-9af3-f1aa36aceeb9.jpg)

**Comment by TomateCardozo** [comment]
i do what u said, name the sprites as _0 and that, but its a problem of the app, because i named like that exactly but still cutting the image, even without changed the size of the texture, still buged and cutted :(

**Comment by Jacky720** [comment]
Sorry, I didn't realize GitHub used angle brackets that way. I've edited my comment to be readable.

You should run the script *in* the tool, using the "Scripts" button. Don't need to go to the source file. Not sure if that helps.

If it doesn't, look for numbers on the texture page entry. You should be able to tinker with "Source position/size" until it encompasses the whole sprite again.

**Comment by TomateCardozo** [comment]
okay im going to try, i let u know if it doesnt work okay?

**Comment by TomateCardozo** [comment]
well, i dont understand very much, if u can give me an example on a video it can be very more understadable, but i try it to do what u said but anyway, i think that or i dont do it correctly or it didnt fixed :(, pls a video if u can :), i dont want to be annoying

**Comment by TomateCardozo** [comment]
hey

**Comment by TomateCardozo** [comment]
are u there?

**Comment by TomateCardozo** [comment]
i found the problem, it is the pulgates of my screen

**Comment by Jacky720** [comment]
Does that mean this issue can be closed?

**Comment by Miepee** [comment]
FWIW pulgadas is spanish for inches. So based on my understanding, sounds like a DPI problem.

**Comment by Miepee** [comment]
going to close this issue, as it's not really actionable. If someone can provide more info, feel free to reopen.
