### ISSUE TITLE
The index values in `for` operator can be resolved as game objects.

### ISSUE THREAD

**Issue by VladiStep** [UnderminersTeam/UndertaleModTool#1250]
### Describe the bug

I just encountered that in "gml_GlobalScript_scr_jevil_check" code entry of Deltarune 1&2.
`for (var k = obj_sneo_friedpipis; k < obj_pipisFireworkGenerator; k++)`
But `for (var i = 0; i < 6; i += 1)`

![image](https://user-images.githubusercontent.com/45438625/228652688-0538e6f0-06d7-43b9-b75b-d97cee3e5321.png)

### Reproducing steps

1. Open "gml_GlobalScript_scr_jevil_check" of Deltarune Chapter 1&2.

### Setup Details

1. UTMT version - https://github.com/krzys-h/UndertaleModTool/commit/b0000b4ff904ed653c040a938635a175ce9bc774

**Comment by Jacky720** [comment]
This is because `self.k` is used as a Kris actor object in a Chapter 1 cutscene. Is there a way to make that resolution object-specific?
