### ISSUE TITLE
Pizza Tower - Debug Controller Script

### ISSUE THREAD

**Issue by ThatCDdev** [UnderminersTeam/UndertaleModTool#1257]
### Problem

I don't know if this is a bit of a stretch, but I want a fix for the Pizza Tower debug controller script
It is located in the Pizza Tower data.win > Code > gml_Object_obj_debugcontroller_Create_0
It will not compile, and reports this error:

![image](https://user-images.githubusercontent.com/84570034/229209147-726c6f5c-c622-43f8-98c8-0624776a5087.png)

I don't know if this is an attempt at obfuscation, a genuine error by the devs, or just if it needs an update to the decompiler.
I have seen this happen multiple times in other Pizza Tower scripts, though I have also seen it happen in other games.
I hope this is fixable, and will be fixed soon.

### Reproducing steps

1. Open data.win from a fresh copy of Pizza Tower
2. Go to Code
3. Search for "gml_Object_obj_debugcontroller_Create_0"
4. Try to open it
5. See error

### Setup Details

![image](https://user-images.githubusercontent.com/84570034/229209871-96670606-10ad-400f-b0c0-29d865521d92.png)
Windows 10 (NT 10)
Pizza Tower _(it's on Steam, can get it cracked)_

**Comment by Jacky720** [comment]
This script decompiles on current bleeding edge.
