### ISSUE TITLE
Can't Expand Menus

### ISSUE THREAD

**Issue by Smug-1** [UnderminersTeam/UndertaleModTool#1295]
### Describe the bug

The side arrow next to certain menus isn't appearing. They used to work after I first booted up the .win file, but afterwards have disappeared? Please tell me if I did something wrong, I'm new to this program and genuinely confused.

### Reproducing steps

I'm not exactly sure what I did to make this happen, sorry!

### Setup Details

1. The version I was using was UTMT 0.5.0.0
2. My operating system is Windows 11
3. The game was Pizza Tower

**Comment by VladiStep** [comment]
Could you screenshot the menu when it *is* available and when it disappears?
