### ISSUE TITLE
Variables/locals are a pain to work with

### ISSUE THREAD

**Issue by Govorunb** [UnderminersTeam/UndertaleModTool#132]
Currently, creating a new script and/or adding variables through the GUI is a thousand-step process that could really see some improvement.
## Adding a Variable
First of all, the most critical issue - creating an UndertaleVariable through the context menu is currently not possible due to them not being an UndertaleNamedResource (so when the editor tries to read the name of the newly created variable, the tool just crashes). This is just a one-line fix, though - I've already compiled it locally (huge thank you for making the build process easy, by the way) and it works perfectly.
However, the instance/global variable count in the editor for the Variable section does not update, though I'm not sure if that breaks anything.
## Adding a Script
The current process for adding a simple no-locals script is:

1. Right-click the Code section and click Add 
2. Name the script (e.g. scr_example)
2.1. Wonder why the empty script failed to disassemble
3. Add a new Code Locals entry
4. Rename it to the script's name (here it'd be scr_example)
5. Add arguments at 0 and go back to the script editor to check
6. Realise it's not working
6.1. Figure out it's because the "scr_example"s are actually two different strings
7. Go to the very bottom of the Strings section, drag the string belonging to the Code object to the Code Locals object, then delete the now duplicate string
8. Set the script's Locals Count to 1 and write the `.localvar 0 arguments`
9. It works! Now after 5-10 minutes of fiddling around you have the empty script you wanted to make.

There's a few steps here that aren't entirely necessary. And even though some of the confusion only appears the first time you try adding stuff (since you already know what the correct steps are later) there's still some unnecessary friction in the creation process.

### Adding Locals
But it gets worse. If you want to have any locals at all in the script, you now must:

- Add a second entry to the Code Locals object (let's name it locvar)
- Make a new variable (currently broken) and set it to Local
  - Drag the "locvar" string into the name field
  - Delete the orphaned "variablexxxx" string
- Update the VarID to the Code Locals index of the variable
- Go back to the script and try doing stuff with the variable
  - Spend 20 minutes asking the higher powers why it's not working
- Look at other scripts, they seem to be working for some reason
  - Notice the second ID that comes after the variable name (e.g. `.localvar 1 extra_ja_vspace 145` in scr_texttype)
- After some more investigating, find out that it was the ordering ID in the string you previously deleted
  - Eventually find out the ordering ID by e.g. creating another variable and using the number 1 less than the new one's
- It works! Whew. Finally.

In my opinion, this could all be greatly simplified.
## Suggestions
I think it would make sense to:

- When changing the type of a variable (possibly from None) to Self/Global, autofill the VarID with the current instance/global count and increment that count
  - I personally can't think of any instances where you wouldn't want to have that happen
- On script creation, automatically generate a Code Locals object and fill it with the 0-arguments pair 
  - Possibly even add a reference to the Locals object to the editor for easier editing
- If the user adds an entry to the Code Locals object,
  - Update the locals count on the Script object
  - If the variable with the name does not exist, create it as Local
  - Add the `.localvar` line assembly equivalent with the ordering ID already on it (please, looking for it is a pain)

P.S.: I've been working with this tool for a bit over a month now, and I love it to bits. This is actually my only major complaint so far, apart from object ordering IDs not being visible anywhere unless they're used in a script. Keep it up!

**Comment by Govorunb** [comment]
Something to also note is that omitting the ordering ID from a `.localvar` line does not throw an error, but you still cannot use the variable. In other words, `.localvar 1 locvar` will be accepted by the assembler just fine, but when you try to use `local.locvar`, you'll get a "Bad Variable" exception. 

I'm not sure if that's how it's supposed to work, but it seems somewhat confusing if it is.

**Comment by krzys-h** [comment]
Yeah, the local vars support is pretty much unfinished, I did just enough of it to get it to work at all. Adding these things is somewhat better from the scripting interface point of view because that is what I do this most often in. I wish I had more free time to fix all issues like this, but if you have any fixes, I'll gladly take pull requests!

**Comment by BreakinBenny** [comment]
How does this work if you plan to add extra game objects or code? Lookit this: I make obj_susiechara (play as Susie) and add her sprites, but then I need to give her code for moving around etc., and I copypaste about everything from obj_mainchara but alter parameters to match Susie…

And of course, it tells me about unsupported bytecode versions...

**Comment by colinator27** [comment]
I might take a try at making this work better soon.

**Comment by Miepee** [comment]
Is this still an issue? Last time I checked it shouldn't be.

**Comment by Jacky720** [comment]
Closing-- Variables and code locals can currently be generated by the compiler and any up-to-date complaints can be made in a new issue.
