### ISSUE TITLE
SaveCodeChanges()

### ISSUE THREAD

**Issue by imirui** [UnderminersTeam/UndertaleModTool#1375]
### Describe the bug

When attempting to save code, the program throws up an error saying "The changes in code editor weren't saved due to some error in "SaveCodeChanges()".

### Reproducing steps

1. Open File
2. Edit code
3. Save code

### Setup Details

I use v:0.5.1.0, the latest version of bleeding edge (Git: a712808) and have a windows 10 computer.
I made an attempt to edit code in Pizza Tower.

**Comment by Reycko** [comment]
your code has an error

**Comment by Jacky720** [comment]
What code were you trying to edit and what did you change it to?

**Comment by Miepee** [comment]
Closing due to lack of info
@imirui feel free to reopen the issue when you provide more info
