### ISSUE TITLE
Out of memory?

### ISSUE THREAD

**Issue by JoaquinClarosGaming** [UnderminersTeam/UndertaleModTool#1392]
### Describe the bug

when i try to import sprites doesn't work

### Reproducing steps

i only use ImportGraphics.csx
and this happened
![image](https://github.com/krzys-h/UndertaleModTool/assets/102455395/3decaa6a-9474-41c4-a911-84b69b9e15a9)

### Setup Details

UndertaleModTool 5.0.0
Windows 10
Pizza Tower

**Comment by Jacky720** [comment]
Make sure your import folder only contains the sprites you want to import, likely no more than 20 at once. If you try to reimport every sprite in the game, you will have a bad time.

**Comment by JoaquinClarosGaming** [comment]
> Make sure your import folder only contains the sprites you want to import, likely no more than 20 at once. If you try to reimport every sprite in the game, you will have a bad time.

Thank you, i was thinking i have to import all
