### ISSUE TITLE
Opening Ch2 on latest UMT Bleeding Edge version causes an error

### ISSUE THREAD

**Issue by DiamondBor** [UnderminersTeam/UndertaleModTool#1397]
### Describe the bug

![image](https://github.com/krzys-h/UndertaleModTool/assets/99621601/7e5faf9b-3dc2-42b5-973b-b5b355c344e7)

That's all, opening ch2 on latest UMT bleeding edge causes that

### Reproducing steps

1. Open DR CH2 on UMT bleeding edge latest version

### Setup Details

1. Latest Bleeding Edge version (from May 23th, 2023) (idk the specific version number and i alr uninstalled it and installed a release version)
2. Windows 11 21H2 (Cause I don't have a TPM or sum so I can't update to 22H2)
3. Deltarune Chapter 2

**Comment by Jacky720** [comment]
I do not know what caused this but it's definitely not the case on current BE.
