### ISSUE TITLE
feel like this isnt a feature and rather me being shitty at coding but... (btw i didnt mean to label it bug but now i cant edit it lol)

### ISSUE THREAD

**Issue by chairfreaker60** [UnderminersTeam/UndertaleModTool#1404]
### Describe the bug

why cant i import sprites to custom made game objects? the option to "add sprite" is greyed out for some reason. and i also dont know how to give a custom made monster a name, text, or acts, and without acts the game crashes if i press on the act button.

### Reproducing steps

none needed

### Setup Details

*i use bleeding edge

**Comment by Jacky720** [comment]
Sprites can be added to objects by dragging them from the sidebar. New sprites can be imported using ImportGraphics.csx, and the code issues are unrelated to the tool and best discussed in the Underminers Discord. Closing.
