### ISSUE TITLE
PageItem error when importing

### ISSUE THREAD

**Issue by MaximosVeLOL** [UnderminersTeam/UndertaleModTool#1407]
### Describe the bug

I keep getting an error talking about "Parameter is not valid" When importing

### Reproducing steps

1. Open Pizza Tower's data.win
2. Make a PageItem
3. Import and find out

### Setup Details

1. 5.10
2. Windows 11
3. Pizza Tower

**Comment by Jacky720** [comment]
Just, making a PageItem? I'm not sure that's ever been valid. PageItems need to point to coordinates on a texture (sheet), and the import functionality edits that sheet. I would recommend ImportGraphics.csx to abstract all of this, anyway, and just go from external PNG (in its own folder) to new sprite.

That error should probably be clarified, though, whether or not it is what I think it is.

**Comment by MaximosVeLOL** [comment]
Thanks!

**Comment by Jacky720** [comment]
Based on that last response, I'm assuming this problem is solved.
