### ISSUE TITLE
TS!Underswap cannot be modified on v0.5.1

### ISSUE THREAD

**Issue by ShorterTuxedo** [UnderminersTeam/UndertaleModTool#1414]
### Describe the bug

Hello,

Trying to mod TS!Underswap results in an error in UTMT:

![image](https://github.com/krzys-h/UndertaleModTool/assets/49613009/f2e3ad35-a983-4002-a568-ac27463f7475)

Is there anyone who knows what's going on? I'm trying to make a traditional Chinese translation for TS!Underswap.
### Reproducing steps

Download a copy of TS!Underswap from GameJolt.

Use UTMT to open data.win

UTMT crashes upon opening data.win of TS!Underswap.

### Setup Details

UTMT version 0.5.1
Windows 10
TS!Underswap - made in GMS 2

**Comment by colinator27** [comment]
This would appear to be a regression in the sequence parsing code... not sure when it occurred, but I know older versions used to be able to load it. (I'm a dev on that game, lol!)

Might need someone to do a bisect to find the offending code/commits, unless we can find it directly.

**Comment by ShorterTuxedo** [comment]
Thank you. May I please ask which version of UTMT worked on TS!Underswap's data.win file?

**Comment by Grossley** [comment]
Please do not close issues that are not properly resolved. Just because it works on older versions does not mean this issue is resolved. This issue will stay open until the problem is corrected on the current version of UndertaleModTool.
