### ISSUE TITLE
03BF9073 problem

### ISSUE THREAD

**Issue by XTMYTYT** [UnderminersTeam/UndertaleModTool#1416]
### Describe the bug

![image](https://github.com/krzys-h/UndertaleModTool/assets/86971741/f142b1f8-9333-4098-9394-3f85e83e4026)

### Reproducing steps

well the picture explains it

### Setup Details

Bleeding Edge
windows 10 version 1809
gm 2022.9

**Comment by H-A-M-G-E-R** [comment]
What game?

**Comment by XTMYTYT** [comment]
pizza tower

**Comment by Jacky720** [comment]
The version of Pizza Tower I keep on hand is 2022.9 and opens on current bleeding edge. Closing.
