### ISSUE TITLE
can't export certain sounds

### ISSUE THREAD

**Issue by filepslmao** [UnderminersTeam/UndertaleModTool#1422]
### Describe the bug

i go to the sounds folder to find the audio i want to export and import, but when i go to "audio file" it plays and exports a different audio.

### Reproducing steps

1 - open the program
2 - go to the sounds folder
3 - find the audio i want (only happens to some of them)
4 - go to audio file
5 - click play/export, and it plays/exports a different sound

### Setup Details

UndertaleModTool version: 0.4.0.4
OS: Windows 10
Gamemaker game: i'm not sure but i was modding the steam version of undertale

**Comment by Miepee** [comment]
@filepslmao can you please provide more info?

**Comment by Miepee** [comment]
Closing due to lack of info.
Please reopen the issue if you have more info to provide.
