### ISSUE TITLE
Automatic code messages get duplicated every time one compiles on Profile Mode.

### ISSUE THREAD

**Issue by Romualdo666** [UnderminersTeam/UndertaleModTool#1426]
### Describe the bug

When you have Profile Mode enabled and you compile in a code with an automatic message (for example,             scr_windowcaption(scr_84_get_lang_string("PROCESS_LOGO_slash_Draw_0_gml_37_0")) // DELTARUNE), the // message will be duplicated.

### Reproducing steps

1. Enable Profile Mode.
2. Get in a code that contains an automatic // message (Example: gml_Object_PROCESS_LOGO_Draw_0 in DELTARUNE).
3. Write something (DO NOT DELETE THE // MESSAGE).
4. Compile.
5. You will notice how the // message duplicates. This will happen each time you compile.

### Setup Details

1. Undertale Mod Tool Bleeding Edge.
2. Windows 11.
3. Deltarune Chapter 1&2.

**Comment by Jacky720** [comment]
These comments are handled by [UndertaleCodeEditor.xaml.cs](https://github.com/krzys-h/UndertaleModTool/blob/master/UndertaleModTool/Editors/UndertaleCodeEditor.xaml.cs#L682), so the appropriate fix to disable if Profile Mode is on and the comments already exist should likely be inserted there.
