### ISSUE TITLE
Index Problem

### ISSUE THREAD

**Issue by JoaquinClarosGaming** [UnderminersTeam/UndertaleModTool#1427]
### Describe the bug

![image](https://github.com/krzys-h/UndertaleModTool/assets/102455395/a3b3b348-d289-4fe3-a5f6-30cbc4a844a5)
it just gives me this error, i just want to edit some sprites but they have index and i think that's the problem, idk what to do

### Reproducing steps

1. put resource repackers
2. and... that's all

### Setup Details

UndertaleModTool 0.5.1.0
Windows 10
Pizza Tower

**Comment by Miepee** [comment]
@JoaquinClarosGaming can you please provide more info?

**Comment by Miepee** [comment]
This is likely improper use of one of these scripts:
![grafik](https://github.com/UnderminersTeam/UndertaleModTool/assets/38186597/ee74db23-f01e-4155-b16f-0da470b70e9e)

AFAIK this is intended behaviour if one is trying to replace a sprite but not specify all frames of it. Will close as invalid.
If you keep having this issue, please open a new one or ask in the Underminers Discord for help.
