### ISSUE TITLE
Sprite imports with an incorrect size

### ISSUE THREAD

**Issue by ghost** [UnderminersTeam/UndertaleModTool#1433]
### Describe the bug

When importing sprites over existing ones in a texture page item, under specific conditions it can resize itself to be larger than the original sprite. So far I've been able to see this issue with one game. This will affect how the sprite appears in game too and on the texture page item as well.

### Reproducing steps

1. Open OverSave-Tale's data.win file
2. go to spr_battle_soul_blue
3. Open one of the texture page items
4. Quite simply, just export the sprite, and import it right back. It should freeze up for a few seconds, and you should see a slightly upscaled preview image of the soul.

### Setup Details

1. I used the latest version of Undertale ModTool, v:0.5.1.0
2. Windows 10
3. As mentioned earlier, I used OverSave-Tale, here's the download link: https://drive.google.com/file/d/1_QWwByWVaHH8O_XDg-s3Xpy9q88kcnYz/view?usp=sharing

**Comment by Miepee** [comment]
Seems fixed, I cant reproduce this with a bleeding edge build.
