### ISSUE TITLE
can't save

### ISSUE THREAD

**Issue by OmarXZ5780** [UnderminersTeam/UndertaleModTool#1435]
### Describe the bug

i was using this tool to add sprites to pizza tower but when i tried to save it. It kept saying this
![Capture d'écran 2023-07-14 194938](https://github.com/krzys-h/UndertaleModTool/assets/139581607/2ac7bf50-3ab1-4451-8817-97301fc0dd93)

### Reproducing steps

i open the pizza tower data which sends me to undertale mod tool. I made sprites and a background so i go to scripts, resource repackers, import graphics and i put in the sprites graphics. it imports but i want to save it. and then the error pops up

### Setup Details

i have GUI window latest release isBundled true isSingleFile true
my os is windows
i was modding pizza tower

**Comment by Jacky720** [comment]
Does this still occur on the current bleeding edge?

**Comment by Miepee** [comment]
Going to close this for now.
If someone confirms that this is still reproducible on current builds, please reopen the issue.
