### ISSUE TITLE
Cannot Create Code

### ISSUE THREAD

**Issue by BethanyClone** [UnderminersTeam/UndertaleModTool#1440]
### Describe the bug

![image](https://github.com/krzys-h/UndertaleModTool/assets/103522845/2771d301-9283-4322-99d6-b37b361ee111)

When I try to create a new code file and save it, I'll get a strange compiler error. When I first downloaded UndertaleModTool it worked fine, but this started as of lately. I've tried everything I know to fix it, but nothing seems to help. 

### Reproducing steps

1. Open UndertaleModTool.
2. Add code.
3. Save code.
4. Crash occurs.

### Setup Details

1. 5.10
2. Windows 10
3. Pizza Tower

**Comment by Jacky720** [comment]
Does this issue still occur on the current bleeding edge?

**Comment by Miepee** [comment]
Going to close this for now.
If someone can reproduce this on a bleeding edge build, please reopen this issue.
