### ISSUE TITLE
Return statements get removed

### ISSUE THREAD

**Issue by kenan238** [UnderminersTeam/UndertaleModTool#1456]
### Describe the bug

I have a function with an if-guard
![image](https://github.com/krzys-h/UndertaleModTool/assets/73741117/4235819c-56f8-45d9-98bc-0dbd3266380d)
I compile, the guard is gone
![image](https://github.com/krzys-h/UndertaleModTool/assets/73741117/82227f9e-1c12-4d57-b474-df02640f551d)
I know that I can just do `return 0;` but it would be great to see this fixed, especially when I open a game's script that has these types of guards and it removes them.

### Reproducing steps

1. Make a function
2. Write an if-guard
3. Write the rest
4. Compile
5. It's gone

### Setup Details

1. I am using UTMT v:0.5.1.0
2. I am on Windows 10
3. I am editing the game Pizza Tower

**Comment by Jacky720** [comment]
Looks like I'm making #1223 the central hub for duplicates of this, so, closing as duplicate.
