### ISSUE TITLE
Fix game not opening in a gms 2023.4+ compiled modified game

### ISSUE THREAD

**Issue by Neybo** [UnderminersTeam/UndertaleModTool#1461]
### Describe the bug

when opening a gms 2023.4+ compiled  game and modifying it 
it doesnt open anymore

### Reproducing steps

placeholder

### Setup Details

1 Bleeding edge
2 windows 11
3 a pizza tower decomp i compiled

**Comment by Jacky720** [comment]
What error message is produced on trying to open the modified game? What did you modify?

**Comment by Miepee** [comment]
Issue is inactionable due to lack of info
 @Neybo feel free to reopen the issue if you provide the requested info.
