### ISSUE TITLE
GMS 2022.1 compilation causing subtle change in Deltarune entry

### ISSUE THREAD

**Issue by nhaar** [UnderminersTeam/UndertaleModTool#1501]
### Describe the bug

If you go on Deltarune 1.10 and try to change gml_Object_o_boxinghud_Draw_0 at all, the compilation will change the code slightly. In the original code, the heathbar won't be visible in the entrance

<img width="629" alt="image" src="https://github.com/krzys-h/UndertaleModTool/assets/38634785/fac57951-4565-498b-8026-5d4f547f962e">

Doing anychange will cause it to start displaying it:

<img width="617" alt="image" src="https://github.com/krzys-h/UndertaleModTool/assets/38634785/0b4f4ecc-acb4-4362-bc98-37b5b32c29f8">

### Reproducing steps

1. Open Deltarune version 1.10 from Steam
2. Change anything in gml_Object_o_boxinghud_Draw_0 and compile

### Setup Details

1. UndertaleModTool v0.5.1.0
2. Windows 11
3. Deltarune v1.10 from Steam

**Comment by Miepee** [comment]
@nhaar can you reproduce this with a bleeding edge build?

**Comment by nhaar** [comment]
I was not able to reproduce it with bleeding edge, so this issue is likely fixed.

There is a minor recompilation artifact, I have no idea if it poses any trouble, but this bit in the disassembly is different:

(before)
```
:[93]
pushi.e 1
```

(after)
```
:[93]
push.i 231204
setowner.e
pushi.e 1
```

There's no difference in the decompiled text

**Comment by Jacky720** [comment]
Are you sure that before/after is in the correct order? `setowner` instructions are used in certain versions of GameMaker for array copy handling, but the difference isn't usually important and it was never implemented into the UTMT compiler.

**Comment by nhaar** [comment]
My bad youre right that the order is reversed

**Comment by Miepee** [comment]
going to close this then.
