### ISSUE TITLE
Cannot open vivid/stasis (GameMaker 2023.4)

### ISSUE THREAD

**Issue by ILuvGemz** [UnderminersTeam/UndertaleModTool#1508]
### Describe the bug

I got a misaligned warning when I tried to open vivid/stasis
<img width="297" alt="image" src="https://github.com/krzys-h/UndertaleModTool/assets/76889022/1bbfff62-8448-4914-b4c5-6bbbd94e6b4b">

<img width="288" alt="image" src="https://github.com/krzys-h/UndertaleModTool/assets/76889022/893daab8-8bee-4d99-8d44-e01185ef40e0">

### Reproducing steps

1. Open Vivid/stasis' data.win

### Setup Details

1. I used UndertaleModTool 0.5.1.0
2. I used Windows 11
3. Game Maker 2023.4.0.113

**Comment by Jacky720** [comment]
Cannot reproduce on current bleeding edge. @ILuvGemz are you still having this issue?

**Comment by ILuvGemz** [comment]
As much as I would like to respond, as more clearer guidelines were announced that disallowed modding, I would like to retract this issue. Apologies for the waste of time and change of heart.
