### ISSUE TITLE
Search.csx doesn't work in Pizza Tower

### ISSUE THREAD

**Issue by averageminecraftplayer** [UnderminersTeam/UndertaleModTool#1513]
### Describe the bug

When using Scripts > Builtin Scripts > Search.csx, it crashes.

### Reproducing steps

1. Use UTMT on a data.win (for me it's Pizza Tower's)
2. Click on "Scripts"
3. Click on "Builtin Scripts"
4. Click on "Search.csx"
5. Click any options
6. Search for something
7. Watch it almost load then crash at the end

### Setup Details

1. 0.5.1.0
2. Windows 11 Beta Insider Build
3. Pizza Tower (https://store.steampowered.com/app/2231450/Pizza_Tower/)

**Comment by Jacky720** [comment]
Is there an error message with the crash?

**Comment by Miepee** [comment]
@averageminecraftplayer can you please provide more info?

**Comment by Miepee** [comment]
Issue is inactionable due to lack of info.
Feel free to reopen the issue with the needed info provided.
