### ISSUE TITLE
A lot of reading misaligned error when opening data.win

### ISSUE THREAD

**Issue by Senjay-id** [UnderminersTeam/UndertaleModTool#1561]
### Describe the bug

A lot of reading misaligned error when opening Zero Sievert data.win

### Reproducing steps

1. open the data.win
2. reading misaligned error pops out, lots of them

### Setup Details

1. UMT Bleeding Edge November Build  Code 64b52a6
2. Windows 10 latest
3. Zero Sievert https://store.steampowered.com/app/1782120/ZERO_Sievert/

**Comment by Miepee** [comment]
Duplicate of #1761
