### ISSUE TITLE
Undertale Mod Tool Error: Reading Out of Bounds.

### ISSUE THREAD

**Issue by UnknownSandwich** [UnderminersTeam/UndertaleModTool#1574]
### Describe the bug

i tried to open my data.win mod file and that error appeared.

Help pleaseee

### Reproducing steps

I closed the file yesterday to sleep, i woke up and tried to open it and that happened.

### Setup Details

Im using undertalemod tool latest version

**Comment by VladiStep** [comment]
What error?

**Comment by Miepee** [comment]
@UnknownSandwich can you provide more info please? What game, what error, and what exact undertalemodtool version?

**Comment by Miepee** [comment]
Closing issue due to being inactionable.
If you have more info, please provide it and reopen the issue.
