### ISSUE TITLE
heya so I tryna to added a sprite/tileset

### ISSUE THREAD

**Issue by DiscardedDog** [UnderminersTeam/UndertaleModTool#1575]
### Describe the bug

so I try to the embedded textures and imported to page item and imported to background 70/bg_tileset but the problem is I got this which it wouldn't let me save date.win from it
![image_2023-12-19_141404722](https://github.com/krzys-h/UndertaleModTool/assets/116447897/cc36a6f8-9276-4a77-9eab-dad77f85ac7d)

### Reproducing steps

1.I add a sprites and import graphics to but an png to sprites that I created.
2.I imported the textures embedded from the sprites
3.I imported to texture page item from texture embedded
4.I did the same thing to imported the page item to bg_tileset
5.I save it and something unexpected happen that it didn't save it

![image_2023-12-19_141801536](https://github.com/krzys-h/UndertaleModTool/assets/116447897/ed4ca1eb-7080-46f1-89b2-b08acf76f72a)

### Setup Details

I'm using version 5.1.0 of the latest released.
I'm using windows 11 64 bits home
I used the UndertaleModTool_v0.5.1.0-SingleFile.zip

**Comment by Miepee** [comment]
@DiscardedDog which game were you using for this?

**Comment by Miepee** [comment]
I will close the issue then unless someone can repro this
