### ISSUE TITLE
ExportAllStringsBetter.cxs error CS0246

### ISSUE THREAD

**Issue by bidoofis** [UnderminersTeam/UndertaleModTool#1615]
### Describe the bug

![image](https://github.com/krzys-h/UndertaleModTool/assets/52582446/5f25f157-c0d8-4846-82d0-4bc617c58f8f)

Can't export strings

### Reproducing steps

1. Open data.win
2. Use ExportAllStringsBetter.cxs

### Setup Details

1. happens on Latest Version (both single file and non-single file)

**Comment by Miepee** [comment]
Please retry it on a bleeding edge version

**Comment by bidoofis** [comment]
Sorry, by "latest version" i meant bleeding edge version. My bad.

**Comment by Jacky720** [comment]
What is your OS? I recall seeing a similar error and I suspect the SaveFileDialog might not be implemented (somehow).
