### ISSUE TITLE
Decompiler Error using Undertale With Jsons (Bleeding Edge)

### ISSUE THREAD

**Issue by angelapuzzle** [UnderminersTeam/UndertaleModTool#1645]
### Describe the bug

This happens after opening an Undertale data.win that has been modified by the UndertaleWithJSONs.csx script
When decompiling some code entries UndertaleModTool behaves weirdly adding comments where it shouldn't and making invalid code.
It doesn't happen on vanilla Undertale itself, but running UndertaleWithJSONs.csx on a vanilla data.win, closing and reopening triggers the bug

![image](https://github.com/krzys-h/UndertaleModTool/assets/71221709/ee7b1c20-3749-479d-9236-65629ff8932f)
![image](https://github.com/krzys-h/UndertaleModTool/assets/71221709/cc772292-85b0-48ae-8b9a-ef4efb774cc5)
![image](https://github.com/krzys-h/UndertaleModTool/assets/71221709/4e3060d6-d3a2-402e-b9b9-e2594a74b92b)
![image](https://github.com/krzys-h/UndertaleModTool/assets/71221709/b2b008b4-56ae-4b45-adc4-66c66d96ffcf)

There are two things i noticed about this bug, 1st it's that the comments are the missing correct code, 2nd it's that this happens only when scr_gettext is used within the code.

### Reproducing steps

1. Open an Undertale data.win
2. Run UndertaleWithJSONs.csx if it hasn't been run already, close and reopen the data.win
3. Open a code entry containing scr_gettext in it

### Setup Details

1. UndertaleModTool Version: Bleeding Edge -  January 13 2024
2. Operating System: Windows 11
3. Game Used: Undertale 1.08

**Comment by Jacky720** [comment]
This has apparently also occurred without the script (courtesy of Spyril) on 0.5.1.0, specifically with `scr_gettext("stat_menu_name")`.
