### ISSUE TITLE
The object pool size mismatch warning crashes CLI.

### ISSUE THREAD

**Issue by VladiStep** [UnderminersTeam/UndertaleModTool#1652]
### Describe the bug

The warning ("Warning - the estimated object pool size differs from the actual size") should only show a message (like in GUI version), but if you launch CLI without the verbose parameter, it will not allow you to load such data file.

### Reproducing steps

1. Open a game with the object pool size mismatch warning through CLI without using the verbose parameter.

### Setup Details

1. UTMT version - https://github.com/krzys-h/UndertaleModTool/commit/9ba5d857ba5326a858c0e66c5fd68f7d764c69cd

**Comment by suphamster** [comment]
Can somebody add this fix https://github.com/VladiStep/UndertaleModTool/commit/ccb3212d217d5aa88e0585db7572944d3b86c28b (create PR) since it was made some times ago without adding to main branch?
