### ISSUE TITLE
Undertale Mod Tool incorrectly flags functions in step code as a issue

### ISSUE THREAD

**Issue by blacklambCZ** [UnderminersTeam/UndertaleModTool#1655]
### Describe the bug

When modding games with GMS2 versions, when editing a step code where theres a existing function, it will say there´s an error.

### Reproducing steps

Open any game with UTMT that uses GMS2, has functions in step code and try edit anything in the step code, it will not save the changes or might break the step code entirely. Also: this can sometimes happen with regular functions too
![Výstřižek](https://github.com/krzys-h/UndertaleModTool/assets/76792760/e4379efd-bb02-4daa-952d-9af0e17461de)

### Setup Details

UTMT Version 0.5.1.0
Operating System: Windows 10
Game: Undertale Yellow

**Comment by Jacky720** [comment]
This is not specifically a problem with the step code, but rather an unnecessary insistence on built-in functions having specific argument counts. PR #1614 adds a config option to disable this, and has builds linked in the comments by github-actions. See also #1612.
