### ISSUE TITLE
TS!Underswap/Yellow issue.

### ISSUE THREAD

**Issue by Fingernailsss** [UnderminersTeam/UndertaleModTool#1658]
### Describe the bug

Attempting to unpack the data.win file for Underswap ver. 2.0, error messages appear instead of just decompiling sprites.
![Screenshot 2024-01-23 121601](https://github.com/krzys-h/UndertaleModTool/assets/107367170/85bfd8b5-d7b5-448f-9a5d-c4c067342d9d)
![Screenshot 2024-01-23 121549](https://github.com/krzys-h/UndertaleModTool/assets/107367170/7833a37c-b7f5-4a3a-850a-b5c1ddcac2be)

and for undertale yellow:

![Screenshot 2024-01-23 121923](https://github.com/krzys-h/UndertaleModTool/assets/107367170/c79a2b48-d812-4461-822c-d457f08cf654)

### Reproducing steps

Download either fangame

Attempt to open data.win file

error

### Setup Details

UndertaleModTool_v0.5.1.0

Windows ver

TS!Underswap Demo 2.0

Undertale Yellow 1.1.0

**Comment by Jacky720** [comment]
Please retry on the bleeding edge build of UndertaleModTool.

**Comment by sawayoshisy** [comment]
UT Yellow confirmed working (opens) with bleeding edge!

**Comment by Archie-osu** [comment]
TS!Underswap v2.0.4 confirmed to open too

**Comment by Fingernailsss** [comment]
I swear to god this why do these programs have to be so inconsistent.

yes, it works.
