### ISSUE TITLE
Can't open data.win on Letifer

### ISSUE THREAD

**Issue by RyanKet** [UnderminersTeam/UndertaleModTool#1664]
### Describe the bug

Whenever I try to open the Letifer data.win, an error states that "An error occured while trying to load: Specified cast is not valid. at 00000774 while reading object Undertale ModLib.UndertalePointerList 1 [[Undertale ModLib.M odels. Undertale ExtensionFile, Undertale ModLib, Version=0.4.0.4, Culture=neutral, PublicKeyToken=null]] at 00000774 while reading object Undertale ModLib.Models.Undertale Extension while reading item 1 of 3 in a list of Undertale ModLib.Models.UndertaleExtension in chunk EXTN"

### Reproducing steps

1. Open UndertaleModTool and try to open the Letifer data.win file
2. You'll get the load error

### Setup Details

UndertaleModTool vers. 0.4.0.4
Windows 10
Letifer Demo: https://store.steampowered.com/app/2294640/Letifer/

**Comment by RyanKet** [comment]
Doesn't work.
\

**Comment by Miepee** [comment]
Can you provide more details? does a new error messsage appear?

**Comment by Jacky720** [comment]
The current bleeding edge and the current game demo just gives the YYC warning and otherwise seems to load fine.

**Comment by Miepee** [comment]
Closing as this doesnt seem to be an issue since it loaded for jacky.
