### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by DancingCat69** [UnderminersTeam/UndertaleModTool#1668]
### Describe the bug

i downloaded the mod tool, i tried to open it with Cat Goes Fishing "data" nad an error appeared that said "DirectCopy error send this too Grossley and make an issue on github" please help 
![obraz_2024-01-31_155222563](https://github.com/krzys-h/UndertaleModTool/assets/158301148/acbcb3f1-9a86-4e88-956e-cb5eb37bee78)

### Reproducing steps

.

### Setup Details

.

**Comment by Jacky720** [comment]
Please ensure that the mod tool has been extracted from its zip and that there's space on your hard drive for app data.

**Comment by Miepee** [comment]
UndertaleModTool does not support getting run from inside a zip. You need to extract it first.
