### ISSUE TITLE
After saving data.win (unchanged) in The Bunny Graveyard, the game stop running

### ISSUE THREAD

**Issue by Muzzma** [UnderminersTeam/UndertaleModTool#1671]
### Describe the bug

The game does not start, but is displayed in the task Manager

### Reproducing steps

1. Save data.win
2. Open game

### Setup Details

1. 0.5.1.0
2. Win 11
3. [The Bunny Graveyard](https://store.steampowered.com/app/1892420/The_Bunny_Graveyard/)

**Comment by BenjaminUrquhart** [comment]
Fixed with #1702 (had similar behavior in the reported game) - I bought this game to test it thanks for the new horror game to experience lol.
