### ISSUE TITLE
Add an option to view a certain room's script

### ISSUE THREAD

**Issue by TristanRoy381** [UnderminersTeam/UndertaleModTool#1674]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

I'm currently working on a mod that my friend is making, and he's been having quite the problems with it. Specifically, the rooms.

We can't really fix a certain issue that pops up, and my friend suggests that it might be from the script of the room. We're also having a hard time finding it, since there's tons in store.

**Comment by Miepee** [comment]
Can you provide more details?

**Comment by Miepee** [comment]
@TristanRoy381 can you provide more info?

**Comment by Miepee** [comment]
This issue is inactionable due to lack of info.
If you have more info to provide, please post it and reopen the issue.
