### ISSUE TITLE
To Be Honest about the old gms 2 and an upcoming gms 3 after gms 2.3 Will you make an converted of beyond bytecode 17

### ISSUE THREAD

**Issue by WarshiDevs** [UnderminersTeam/UndertaleModTool#1676]
### Which component should be improved?

Decompiler

### Describe your feature suggestion in more detail

and also another thing to mention is I wanted to make Nintendo Switch undertale to be like undertale yellow for Game Maker Studio 2.3, and I feel that is a good way to added a new options for little more advances stuff of it.

and yes when I converted bytecode 16 to 17 on undertale 2.0.6 to 2.2.2 it's seem that it's doesn't want to works butI guess you guys can fixed that problem, Until then I'll see you on the flip side at least.

**Comment by Yule42** [comment]
There is no bytecode version after 17. Also, upgrading anything to a new version is ill-advised because changes may break the game.
