### ISSUE TITLE
An error occured while trying to load: Root Chunk is nsta not FORM

### ISSUE THREAD

**Issue by UnknownSandwich** [UnderminersTeam/UndertaleModTool#1678]
### Describe the bug

My data.win file got deleted because my father uninstalled a game, and that data.win file was inside the game's folder. Then i used recuva to restore it but when i tried to open, i got this error "An error occured while trying to load: Root Chunk is nsta not FORM"

### Reproducing steps

![Bulbfish](https://github.com/krzys-h/UndertaleModTool/assets/154335079/899b35d8-0eb7-4120-a423-f40a53bb9e01)
i got a screenshot of the error.

### Setup Details

Im using UndertaleModTool latest version.

**Comment by Jacky720** [comment]
Sounds like the restoration failed. How big is the restored file? If you have a hex editor, what does it look like with that?

**Comment by UnknownSandwich** [comment]
53.418KB is the size of the restored file.

**Comment by UnknownSandwich** [comment]
54.699.846 bytes in the hex editor

**Comment by UnknownSandwich** [comment]
> Sounds like the restoration failed. How big is the restored file? If you have a hex editor, what does it look like with that?

its 53.418KB

**Comment by Jacky720** [comment]
Okay, but what do the actual contents look like in the hex editor?

**Comment by UnknownSandwich** [comment]
> Okay, but what do the actual contents look like in the hex editor?

![image](https://github.com/krzys-h/UndertaleModTool/assets/154335079/8ee7863e-1bf8-465b-8f24-e25d4d9ce9cd)
this you mean?

**Comment by Jacky720** [comment]
Hmm, that doesn't look like a normal data.win file... But I don't see the root chunk "nsta" (root chunk is the first four bytes in a data file) either, which is weird. You'll probably have to reinstall the game and redo your changes.

**Comment by UnknownSandwich** [comment]
thats unfortunate.

**Comment by Miepee** [comment]
If the file gets deleted and you're trying to recover it with external tools, theres no guarantee that the file will be exactly as before
closing as UTMT is not the issue here.
