### ISSUE TITLE
Help me fix this error i can`t open my hecking mod!

### ISSUE THREAD

**Issue by hatty1888124** [UnderminersTeam/UndertaleModTool#1679]
### Describe the bug

![Desktop Screenshot 2024 02 13 - 10 17 14 77](https://github.com/krzys-h/UndertaleModTool/assets/92175043/7e8a84b0-0bc5-4a49-bb8a-791a5fdcf438)
![Desktop Screenshot 2024 02 13 - 10 23 22 90](https://github.com/krzys-h/UndertaleModTool/assets/92175043/1b7814d4-2e75-46bf-910a-07c4b7c1badf)
![Desktop Screenshot 2024 02 13 - 10 23 24 55](https://github.com/krzys-h/UndertaleModTool/assets/92175043/0708cdf9-3024-4d8b-8391-11d867687998)
![Desktop Screenshot 2024 02 13 - 10 23 27 30](https://github.com/krzys-h/UndertaleModTool/assets/92175043/ff7a1803-b006-46c6-a519-72fe62c45232)

### Reproducing steps

I just opened my pizza tower mod and it brings me 3 warning and an error

### Setup Details

i use undertalemodtool community edition but i also tried with normal undertalemodtool but it still didn`t worked

**Comment by Miepee** [comment]
@hatty1888124 does this only happen on your modded version, or on vanilla pizza tower as well?

**Comment by Miepee** [comment]
This issue is inactionable, and you haven't responded in over a month.
Feel free to reopen when you have more info to provide
