### ISSUE TITLE
"The estimated object pool size differs from the actual size." on TS!Underswap.

### ISSUE THREAD

**Issue by Zatten-lang** [UnderminersTeam/UndertaleModTool#1684]
### Describe the bug

![image (1)](https://github.com/UnderminersTeam/UndertaleModTool/assets/81698936/ca278753-931d-477b-b51d-2a8d53f77203)

### Reproducing steps

1. Open UndertaleMODTOOL
2. Import data.win
3. See Error

### Setup Details

1. [UndertaleModTool v0.5.1.0](https://github.com/UnderminersTeam/UndertaleModTool/releases/tag/0.5.1.0)
2. Windows 10
3. TS!Underswap by TeamSwitched https://gamejolt.com/games/tsunderswap/160094

**Comment by Miepee** [comment]
@Zatten-lang please retest this on a bleeding edge build.
