### ISSUE TITLE
Heya I just got GMLive extentsion from gamemaker marketplaces store

### ISSUE THREAD

**Issue by WarshiDevs** [UnderminersTeam/UndertaleModTool#1690]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

spent my money to purchase this plugins and download the gms 2 version from the online store, however I want to know is there a way to imported gmlive from the yymp to data.win for undertale stars and omnius so I can run the game and change the sprites, code, tileset, etc without clsoing the windows and re-run it.

Please let me know about it.

also heres a link for it: https://marketplace.gamemaker.io/assets/5992/gmlive-gml-gms1-2-livecoding
![image_2024-02-22_184153384](https://github.com/UnderminersTeam/UndertaleModTool/assets/116447897/1072518c-c49c-4603-ba24-c89b64937e4a)
![image_2024-02-22_184202719](https://github.com/UnderminersTeam/UndertaleModTool/assets/116447897/86267f3e-ba10-478f-b480-3c74451519bc)
![image_2024-02-22_184210637](https://github.com/UnderminersTeam/UndertaleModTool/assets/116447897/ec76ae07-8c05-4740-9968-307aaec4dbb9)
![image_2024-02-22_184217618](https://github.com/UnderminersTeam/UndertaleModTool/assets/116447897/b7b3a3a5-d156-4413-a56e-30ce39496fc8)
![image_2024-02-22_184224433](https://github.com/UnderminersTeam/UndertaleModTool/assets/116447897/6655105c-6bd3-402d-8144-37f4a139d0e3)

**Comment by rynogg** [comment]
1) This is Undertale Mod Tool, not GameMaker support.
2) You cannot import a GameMaker Studio development plugin into a compiled game data file (data.win).  That is not how that works at all.  Undertale Mod Tool does not support livecoding, nor can it use GameMaker Studio plugins.
3) You're stupid and you suck.

**Comment by Dobby233Liu** [comment]
> Undertale Mod Tool does not support livecoding, nor can it use GameMaker Studio plugins.

You can import GM extensions to data.win with some work, doubt GMLive will work well with UMT though.

> anyways I can prove you of what I did but I don't think you will ever listen to me and I don't feel safe from you I'm gonna talk to the staff

I honestly thought you were going to make an alt from this

**Comment by Dobby233Liu** [comment]
Oh right I remember what gmlive needs
- Streaming output of the runner's stdout ("output" in GMS2 IDE)
- A .yyp project
\2. will certainly be hard to get and puts you in legal risk

**Comment by BenjaminUrquhart** [comment]
I haven't used GMLive before, but from what I see it's designed around the Gamemaker Studio IDE (which isn't a factor here). So yes, you could in theory import it but it wouldn't really do that much by itself.

**Comment by rynogg** [comment]
> You can import GM extensions to data.win with some work, for example nik has made a UMT script for importing his NekoPrescene before, doubt GMLive will work well with UMT though.

I was unaware of this before initially making my post.  I really should've actually checked before making a declarative statement like that.  I appreciate the correction.

> one last thing if you ever want talk to me then feel free to friend request me on discord warshi_official

I will not :)

**Comment by colinator27** [comment]
We cannot provide any support for trying to use GMLive in UndertaleModTool, as it just won't work at all. It's only designed for use on your own GameMaker projects, in GameMaker.
