### ISSUE TITLE
Norton 360 labeled UndertaleModCli.exe and .dll as viruses

### ISSUE THREAD

**Issue by Devin-SAA** [UnderminersTeam/UndertaleModTool#1700]
### Describe the bug

When I launched the app for the first time (after Windows SmartScreen warned me, which tends to be normal), Norton 360 labeled both `UndertaleModCli.exe` and `UndertaleModCli.dll` as a threat called `WS.Reputation.1`. Is it something up with Norton, or not?

### Reproducing steps

1. Download and set up Norton 360
2. Open `UndertaleModTool.exe`

### Setup Details

1. Version: Bleeding Edge build 2/26/2024
2. OS: Windows 11 build 22631.3155 (v23H2)
3. Game: Sonic.exe: The Disaster 2D Remake

**Comment by Archie-osu** [comment]
Norton 360 is a very unreliable antivirus engine in the first place, similar to McAfee.

You could try reporting the file to them as non-malicious, but you'd probably be talking to some bot.

I suggest you just get rid of Norton and use a more reputable AV engine - Windows Defender is already built into Windows and is pretty good at its job. If you want some 3rd party tool, I think Bitdefender is a solid choice.
