### ISSUE TITLE
WHERE IS THE EXE FILE AT

### ISSUE THREAD

**Issue by PizzaTowerModding** [UnderminersTeam/UndertaleModTool#1705]
### Describe the bug

I CANNOT FIND IT PLASE HELP ME AAAAAAA

### Reproducing steps

literally none.

### Setup Details

Master version
Windows 8.1

**Comment by Miepee** [comment]
On the releases page:
https://github.com/UnderminersTeam/UndertaleModTool/releases/tag/0.5.1.0

**Comment by PizzaTowerModding** [comment]
miepee what the fu-

**Comment by PizzaTowerModding** [comment]
this isn't completed dude are you drunk?

**Comment by Jacky720** [comment]
Miepee provided the link to the download page that contains a zip with the exe file (UndertaleModTool_v0.5.1.0.zip).

**Comment by Miepee** [comment]
If you need further assistance with unzipping a file and finding the exe in a zip, feel free to ask around in the Underminers Discord server
