### ISSUE TITLE
not sure if this is a bug or just anti-umt

### ISSUE THREAD

**Issue by Tritonico** [UnderminersTeam/UndertaleModTool#1712]
### Describe the bug

tried to open a game and this error happens:
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/97292852/96df2676-f549-4cee-8143-7d0ed7fe8011)

### Reproducing steps

1. Opened a game file... it's not allowed to be disclosed to public, but yeah that's it, just tried to open the data.win
2. the error

### Setup Details

1. bleeding edge (0.5.1.0)
2. Windows 10
3. ...once again... uh... the build is private... but here's the game: https://gamejolt.com/games/disaster2dr/780541 (not like that's gonna help though)

**Comment by Tritonico** [comment]
grah sorry I forgot to put the game loading error label...

**Comment by BenjaminUrquhart** [comment]
Not much we can do until this version is public, the one on the page loads fine.

**Comment by Tritonico** [comment]
oh by the way the issue was that there was a groundbreaking glitch in a script so it got patched up and now it works fine, sorry for disturbing.
