### ISSUE TITLE
script compile error string export 

### ISSUE THREAD

**Issue by Erased-Username** [UnderminersTeam/UndertaleModTool#1732]
### Describe the bug

![image-293](https://github.com/UnderminersTeam/UndertaleModTool/assets/66317576/1193fac9-51b4-408b-9e37-07b77c2b7aa7)

### Reproducing steps

string export

### Setup Details

idk not my screenshot I'm just posting so grossley will be reminded

**Comment by Miepee** [comment]
duplicate of #1572
