### ISSUE TITLE
Round-tripping when disassembling

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [UnderminersTeam/UndertaleModTool#1736]
### Which component should be improved?

Decompiler

### Describe your feature suggestion in more detail

I don't know if this feature already exists. For the disassembler not the decompiler.

**Comment by CST1229** [comment]
> Sorry for the very late response, but the disassembler already exists.

I think they mean making the disassembler round-trip (could be either related to number rounding or just making sure all scripts re-assemble correctly), not adding a disassembler.

**Comment by Miepee** [comment]
The disassembler already is round-tripping.
