### ISSUE TITLE
data.win doesn't open, errors open up

### ISSUE THREAD

**Issue by throwaway2041** [UnderminersTeam/UndertaleModTool#1740]
### Describe the bug

Opening the data.win file included in Tribal Hunter's file explorer shows this.
![UndertaleModTool_7z95EoTQ89](https://github.com/UnderminersTeam/UndertaleModTool/assets/168415315/c2b689b1-941f-486b-bfdc-da203e4fa092)
![UndertaleModTool_wrykFkKDJz](https://github.com/UnderminersTeam/UndertaleModTool/assets/168415315/06804388-dec9-4445-bf76-e756a952ac69)

### Reproducing steps

1. Run UMT
2. Open data.win
3. Errors

### Setup Details

1. 0.5.1.0 UMT
2. Windows 11 Pro (latest update, not dev preview)
3. Tribal Hunter (GOG, 17+) https://www.gog.com/en/game/tribal_hunter

**Comment by throwaway2041** [comment]
Additionally, this worked before, both with an older version of UMT and Tribal Hunter.

Thanks if help.

**Comment by throwaway2041** [comment]
How do I use the bleeding edge version? I'm not a very Linus Tech Tips indiviudal

**Comment by Jacky720** [comment]
You download the last "GUI" zip file, then extract that and run it like the normal release.

**Comment by throwaway2041** [comment]
I extract the GUI zip, and then put in bleeding edge? I'm confused.

**Comment by maxiterr1** [comment]
Run the exe on the folder

**Comment by throwaway2041** [comment]
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/168415315/5ee155e0-4db8-4272-8c03-2205cc8d2ef2)
That doesn't do much of nothing, it just shows command prompt for me.

**Comment by Jacky720** [comment]
That's a CLI version, not a GUI version. The GUI versions are the last four downloads before the source code.

**Comment by throwaway2041** [comment]
Yes I understood that bit, however
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/168415315/e876756a-29ee-41de-bffd-feddec5ac61f)
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/168415315/a14615f1-9071-475d-8b06-5663fe8db730)
That's the one with the issues.
I can't do much, right?

**Comment by Jacky720** [comment]
Are you positive that's a GUI build downloaded from the Bleeding Edge page linked by maxiterr1? Bleeding edge builds are supposed to show the Git commit in the header bar after "v0.5.1.0", as in "v0.5.1.0 - (Git: 82cb64c)".

**Comment by throwaway2041** [comment]
Redownloaded the GUI Bleeding edge and it shows the same title, and it's working now!
Thanks Jacky720!
