### ISSUE TITLE
Error when opening data.win file

### ISSUE THREAD

**Issue by Zendirovich** [UnderminersTeam/UndertaleModTool#1741]
### Describe the bug

When opening the data.win file the following error occurs

### Reproducing steps

![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/142331508/f8495f9d-c253-478d-95e5-927f638f6563)

### Setup Details

Version: latest version
OS: Windows 10
Game: https://pigeondan.itch.io/goobers-troubles

**Comment by maxiterr1** [comment]
The problem is that this game has been created with the latest version of GameMaker which is not supported yet.

**Comment by Dobby233Liu** [comment]
Please check whether #1722 fixes it (build: https://github.com/UnderminersTeam/UndertaleModTool/pull/1722#issuecomment-2034617719)

**Comment by Jacky720** [comment]
It does.
