### ISSUE TITLE
Easy scale not working

### ISSUE THREAD

**Issue by 616-com** [UnderminersTeam/UndertaleModTool#1752]
### Describe the bug

When i try to do the object rescaling with the mouse (by dragging from an object's border) i can't rescale the object

### Reproducing steps

try to rescale with the mouse

### Setup Details

1. lastest version of undertalemodtool bleeding edge
2. Windows 10 Pro
3. this mod of an game (i was optimizing it by firstly stretching all collisions) https://gamebanana.com/mods/480216 (btw this mod is not mine and im gonna post the optimizated version if the creator lets me)

**Comment by CST1229** [comment]
Vanilla UTMT does not have scaling by dragging object edges.
