### ISSUE TITLE
Zero Sievert "reading misaligned at 013D36AC, realigning back to 013D36B0"

### ISSUE THREAD

**Issue by ajdrigs** [UnderminersTeam/UndertaleModTool#1761]
### Describe the bug

Hello, I followed the wiki for modding Zero Seivert, I'm using Modtool v:0.5.1.0 When I try to open the data.win it displays this 
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/51725990/198e8ef5-f99e-49b5-980f-cf2d65d83f5f)

### Reproducing steps

Open data.win in the games directory, installed via Steam.

### Setup Details

1: Modtool v:0.5.1.0 https://github.com/UnderminersTeam/UndertaleModTool/releases/download/0.5.1.0/UndertaleModTool_v0.5.1.0.zip
2: Windows 10 Home Version 22H2
3: https://store.steampowered.com/app/1782120/ZERO_Sievert/ 
https://gamemaker.io/en/showcase/zero-sievert

**Comment by Jacky720** [comment]
Have you tried the current [bleeding edge](https://github.com/UnderminersTeam/UndertaleModTool/releases/download/bleeding-edge/GUI-windows-latest-Release-isBundled-true-isSingleFile-true.zip) build of UTMT?

**Comment by ajdrigs** [comment]
> Have you tried the current [bleeding edge](https://github.com/UnderminersTeam/UndertaleModTool/releases/download/bleeding-edge/GUI-windows-latest-Release-isBundled-true-isSingleFile-true.zip) build of UTMT?

Just tried, and It gave the same error.

**Comment by subtank** [comment]
just using the new one build still have same issue [bleeding edge](https://github.com/UnderminersTeam/UndertaleModTool/releases/download/bleeding-edge/GUI-windows-latest-Release-isBundled-true-isSingleFile-true.zip)

**Comment by JMak22** [comment]
Same issue, different message.

data.win from Steam game directory, stable version of UTMT, didn't try bleeding edge, Win 11.

![Screenshot 2024-06-03 011915](https://github.com/UnderminersTeam/UndertaleModTool/assets/112358835/dfa150ac-0c3a-4978-af9f-700376c16027)

**Comment by MichaelEpicA** [comment]
Bleeding Edge just gives this for an entirely different game.

**Comment by Senjay-id** [comment]
The latest bleeding edge version fixed this issue, I've tested it
