### ISSUE TITLE
Undertalemodtool.dll false positive on Malwarebytes

### ISSUE THREAD

**Issue by fe3a8b63** [UnderminersTeam/UndertaleModTool#1765]
### Describe the bug

![scanner](https://github.com/UnderminersTeam/UndertaleModTool/assets/169941095/f5ea1f90-c7b3-45d0-8f68-b9c5f0e619a2)
![virustotal](https://github.com/UnderminersTeam/UndertaleModTool/assets/169941095/50e37641-091c-443d-bad0-e7c03c1c615b)

I know it isnt a bug, but it will throw people off. Ill see if I can contact MalwareBytes to correct this but still

### Reproducing steps

Simply scan any version that is not single file via Malwarebytes

### Setup Details

Any non single file version after 5.0 gets marked as such

**Comment by Miepee** [comment]
This is something that some AV do, where we can't do anything about it.
