### ISSUE TITLE
My character is stuck to a specific place

### ISSUE THREAD

**Issue by Randomtd2drModder** [UnderminersTeam/UndertaleModTool#1771]
### Describe the bug

There is a line in sonic.exe the disaster 2d that, when i spawn, restricts me to a specific area that i can't leave.Making me unable to move around and stuff...

### Reproducing steps

1. open Undertale mod tool
2. Edit a sprite (changing colors etc)
3. launch sonic.exe the disaster 2d remake
4. play a game
5. see the line
6. you can't move around

### Setup Details

I just changed the color of this sprite
![spr_amy_lookup](https://github.com/UnderminersTeam/UndertaleModTool/assets/170870394/04f9d46a-0399-4efd-a0bc-9b59f7fe3e97)
but it makes it really unable to move the character in the game, please help

**Comment by Miepee** [comment]
Please provided a link to the game. @Randomtd2drModder

**Comment by sonic3XE** [comment]
@Randomtd2drModder, is the game came from Game Jolt?

**Comment by Miepee** [comment]
Going to close the issue as the reproduction steps are too vague.
Feel free to reopen if more specific instructions are provided
