### ISSUE TITLE
error then i try launch undertale data.win

### ISSUE THREAD

**Issue by zick190210** [UnderminersTeam/UndertaleModTool#1797]
### Describe the bug

![Снимок экрана 2024-06-03 140712](https://github.com/UnderminersTeam/UndertaleModTool/assets/171569777/4022e759-7021-443d-a98c-374e271d5f7d)
![Снимок экрана 2024-06-03 140718](https://github.com/UnderminersTeam/UndertaleModTool/assets/171569777/26757203-00e7-4cdc-be12-db556662f35e)
 i try launch undertale data.win 
 and this gives error (idk why)

### Reproducing steps

1.open data.win
2.done!

### Setup Details

1. lastest umt
2. windows 11 (windows 10 too)
3.Undertale

**Comment by Miepee** [comment]
Which version of undertale?

**Comment by zick190210** [comment]
1.03 (lastest)

**Comment by Jacky720** [comment]
The latest PC version of Undertale is 1.08. Is this a non-English translation? Can you share any relevant links (e.g. to download this version of Undertale, since my versions from Steam/GOG work) or screenshots (e.g. the start menu with the version number)?

**Comment by Miepee** [comment]
error message does read similar to #855 ...

**Comment by zick190210** [comment]
> The latest PC version of Undertale is 1.08. Is this a non-English translation? Can you share any relevant links (e.g. to download this version of Undertale, since my versions from Steam/GOG work) or screenshots (e.g. the start menu with the version number)?

https://drive.google.com/file/d/1m1iFaqG6IelBgZd2vkehmT1pctkFpOWF/view?usp=sharing
(friend send me it through TELEGRAM)

**Comment by zick190210** [comment]
https://thelastgame.ru/undertale/
new version do it too

**Comment by BenjaminUrquhart** [comment]
I'm gonna assume this is a Russian translation made with older tooling such as Translatale, which there is an issue open about already. 

With that being said, we don't provide support for pirated versions of Undertale.

**Comment by Jacky720** [comment]
I've deleted the replies containing download links, as they were for the full game. Equivalent patches uploaded on #855.
