### ISSUE TITLE
The program deletes the line of code below the line with "scr_gettext" when saving.

### ISSUE THREAD

**Issue by YurangaW** [UnderminersTeam/UndertaleModTool#1805]
### Describe the bug

In the lines with "scr_gettext", the program adds a comment with the contents of this line in English. But sometimes the next line of code is written to the comment instead, and the line itself is deleted. This, one line will be erased every time you save file.
It looks like each file has no more than one line deleting the others.
![Screenshot_614](https://github.com/UnderminersTeam/UndertaleModTool/assets/102863746/86647bdf-71b1-498f-b1c2-8eb9d4049763)

### Reproducing steps

Variant 1:
1. Open the Undertale's data.win file.
2. Open code file "gml_Object_obj_papyrus8_Step_0".
3. Line 331 deletes line 332.

Variant 2:
1. Open the Undertale's data.win file.
2. Open code file "gml_Object_obj_papyrusboss_Step_0".
3. Line 928 deletes line 929.

Variant 3:
1. Open the Undertale's data.win file.
2. Open code file "gml_Object_obj_glydeb_Step_0".
3. Line 127 deletes line 128.

### Setup Details

1. UndertaleModTool version: 0.5.1.0.
2. Operating system: Windows 10.
3. GameMaker Game: Undertale, V1.08, Steam version.
4. Game linc: https://store.steampowered.com/app/391540/Undertale/

**Comment by Jacky720** [comment]
Already fixed on bleeding edge, see #1695.
