### ISSUE TITLE
Some numbers are still not displayed correctly

### ISSUE THREAD

**Issue by GFOXSH** [UnderminersTeam/UndertaleModTool#1810]
### Describe the bug

![1](https://github.com/UnderminersTeam/UndertaleModTool/assets/15711761/f6739020-213e-4d28-9bde-6d0468caac65)

### Reproducing steps

Assign any variable the value 0.07 or otherwise use this number in code

### Setup Details

1. Latest Bleeding Edge
2. Windows 10 22H2
3. https://gamejolt.com/games/nxtale/636375

**Comment by Jacky720** [comment]
Bleeding edge builds typically show the last Git commit in their title bar. Also, I can't reproduce this. Please double-check your tool version.
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/32578221/9ee92eec-1b3c-4bef-8168-0e175bdf73c2)

**Comment by GFOXSH** [comment]
OK, I guess I didn't really have the latest version. Sorry to bother you.
