### ISSUE TITLE
Problem with TS!Underswap pool size differs from actual size

### ISSUE THREAD

**Issue by FellSlam1** [UnderminersTeam/UndertaleModTool#1815]
### Describe the bug

Pretty self explanatory. Any fix?

### Reproducing steps

1. I try to open the game
2. Open the win.
Problem appears
![Captura de pantalla (834)](https://github.com/UnderminersTeam/UndertaleModTool/assets/173864853/8fcaf365-ca81-4402-9195-79c5a4a35c06)

### Setup Details

Windows 11

**Comment by Jacky720** [comment]
Duplicate of #1684.
