### ISSUE TITLE
UTMT throws an exception when trying to save data with new tiles

### ISSUE THREAD

**Issue by Senjay-id** [UnderminersTeam/UndertaleModTool#1816]
### Describe the bug

When trying to save the data with tiles being added using a script it throws an error
The layer tile isn't even added to the room

### Reproducing steps

1. Open the data.win and run the attached script file inside utmt
[script.zip](https://github.com/user-attachments/files/16027152/script.zip)

2. Save the data
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/110238760/7482634d-3101-4209-9db7-8eb5bceeb236)

### Setup Details

1. Latest bleeding edge
2. Windows 10 Latest
3. [ZERO Sievert](https://store.steampowered.com/app/1782120/ZERO_Sievert/)

**Comment by Miepee** [comment]
This is working as expected. See the documentation:
```cs
    /// <summary>
    /// The list of layers this room uses. Used in Game Maker Studio: 2 only, as <see cref="Backgrounds"/> and <see cref="Tiles"/> are empty there.
    /// </summary>
    public UndertalePointerList<Layer> Layers { get => _layers; set { _layers = value; UpdateBGColorLayer(); OnPropertyChanged(); } }
    ```

**Comment by Senjay-id** [comment]
All this time I'm using a wrong function.... welp tyvm for taking a look at it
