### ISSUE TITLE
I need help 

### ISSUE THREAD

**Issue by Tiddly-Berry54** [UnderminersTeam/UndertaleModTool#1818]
### Describe the bug

![nahh](https://github.com/UnderminersTeam/UndertaleModTool/assets/174626737/cf8dd8aa-7079-4b3c-a262-ed9a11aec73e)
idk what this means but i rlly need help

### Reproducing steps

i opened my data.win file but this came up

### Setup Details

im in windows 10 using undertale 1.08 and the gui undertale mod tools bundle latest ver for windows

**Comment by CST1229** [comment]
do not run undertalemodtool from its zip file, that will put _only_ the exe in a temporary directory and it will not have access to any of the other files it needs. instead, extract the zip into a folder and run undertalemodtool from there
