### ISSUE TITLE
Roadmap Plans

### ISSUE THREAD

**Issue by Kneesnap** [UnderminersTeam/UndertaleModTool#182]
These are plans outlined by @colinator27 and me to revamp UndertaleModTool.
This will serve as a roadmap for the tool.

**Long-term Plans:**
 - Sprite management improvements. Managing textures and etc more cleanly. (Clarification below)
 - History tracking / patch files to apply mods directly without scripts. Will need some way of resolving conflicts if multiple mods are applied.
 - Extension Editor
 - Audio Player?
 - Built-in batch exporter of non-code resources.
 - Per-game or Per-decompile configurations. For instance, right now there are Undertale / DR specific variables in the type resolver. We could allow for per-game configs which could add documentation, and include variable types per-game.
 - UI Rewrite. Wants: Cross-platform, multi-language support, faster than WPF / can have syntax highlighting with large scripts, even while editing.

**Short-term Plans:**
 - Continue improving the compiler and fixing any bugs that show up.
 - Continue improving the decompiler and fixing any bugs that show up. Also, making sure the decompiler outputs code as close to the real code as possible. Also, maybe eventually cleanup.
 - The goal is to make it so if we took a game, decompiled all its code, then recompiled it, the resulting bytecode would match the original 1:1. We should write a unit test for this.
 - Compatibility improvements with various GMS games.
 - https://github.com/krzys-h/UndertaleModTool/issues/112
 - https://github.com/krzys-h/UndertaleModTool/issues/46

**Current Changes for next release:**
 - A built-in UTMT compiler, all courtesy of @colinator27 
 - Bytecode 14 support https://github.com/krzys-h/UndertaleModTool/commit/57574612df04e3562c9c031ed7d3f0f2a63834c2 @colinator27
 - Support for assignment statements such as +=, -=, ++, --, etc. (Only with accessors right now. The bytecode for a = a + 1 and a += 1 are identical, so we can't determin them) https://github.com/krzys-h/UndertaleModTool/commit/5d882c334622f36ae2785a6238b1c3ab26f19aaa @colinator27
 - Fixed room data mis-type of "Stretch" variable. https://github.com/krzys-h/UndertaleModTool/commit/9e7ea70577a2f138dc5b0c4763d8c3a63d801404 @Kneesnap
 - Fixed decompiling with statements in loops. https://github.com/krzys-h/UndertaleModTool/commit/c47266f9098aa5b6dac3856f7e28bd513c2c0c65 @Kneesnap
 - Fixed selecting large amounts code (such as with Ctrl + A) crashing UTMT @Kneesnap

**Comment by Kneesnap** [comment]
Bytecode 14 support would be nice.

**Comment by colinator27** [comment]
Clarification for sprite management improvements- the ultimate vision I have is to be able to cleanly edit the frames of each sprite image without having to manually deal with the texture pages and texture entries. It should be able to auto-manage that for you, maybe with a few dialogs asking for the specifics like "you added a frame, make a new texture page?"

**Comment by colinator27** [comment]
This would be more of a UndertaleModLib thing, but maybe we could completely re-export the texture pages themselves with the information we have, using the same algorithm the compiler does (if we look into it).

On a related note, for mods and their compatibility between each other, there should just like, be a simple function to add a sprite or modify one, updating others to make it fit/work, even if that means making another texture page.

**Comment by colinator27** [comment]
> Bytecode 14 support would be nice.

https://github.com/krzys-h/UndertaleModTool/commit/57574612df04e3562c9c031ed7d3f0f2a63834c2

**Comment by colinator27** [comment]
Another thing to add- this: https://github.com/krzys-h/UndertaleModTool/issues/112

**Comment by colinator27** [comment]
Another UI feature - https://github.com/krzys-h/UndertaleModTool/issues/46

**Comment by Kneesnap** [comment]
Yes, I like that. Being able to have automated texture management.

**Comment by colinator27** [comment]
Here are some decompiler revamp/rewrite notes:

- Will need better pattern matching: we don't want a ton of convoluted if statements
- Will need cleaner loop detection and control flow code in general - needs to be commented thoroughly
    - Also needs to support unused/unnecessary blocks etc.
- Should support decompiling to a base AST-type structure, without any distinct code formatting involved.
    - A separate class/classes can handle printing the code, with modifiable settings like indentation, where to put newlines, etc.
- Better asset type detection - we need an Analyze kind of mechanism in the program to decompile everything into a cache, figure out where variables are referenced
    - Each object will need a list of public variables
    - All asset references discovered will be given a special container class so that references can be updated when IDs change
    - All variables will be checked to see what functions/variables they are assigned to, if there's ONLY one type inferred, then it'll become that type, otherwise
      it will be unknown. When checking the functions/variables, the values must be in the range/valid IDs to count, otherwise they're ignored (doesn't stop it altogether, though)
    - Need to handle arrays and other data structures - for the time being, it can probably be user-set, but later we could try doing a lot of analysis of the code, figuring out
      special cases with non-constants etc.
- A useful feature for our code convenience and user experience would be to keep a database of all the variables used, including self/global/local
    - Self belongs to an object resource
    - Global belongs to UndertaleData
    - Local belongs to an UndertaleCode
    - These could be searched and identified easily internally and externally - this info will be public
- Find / Replace functionality, using the compiler to recompile
    - In an UndertaleCode scope
    - ...and a global scope, using the decompiled cache mentioned earlier

**Comment by Kneesnap** [comment]
Maybe conceptualizing the assembly as a tree which branches with each 'b', 'bf', 'bt', etc, would make it  much easier to work with when turning assembly back into GML. (Note: This is separate from the output AST)

**Comment by colinator27** [comment]
> Maybe conceptualizing the assembly as a tree which branches with each 'b', 'bf', 'bt', etc, would make it much easier to work with when turning assembly back into GML. (Note: This is separate from the output AST)

Well, it basically already does, but just in a somewhat messy way.

**Comment by Kneesnap** [comment]
Yes, well, the current way it's organized leaves a lot to be desired. I want to actually structure it like a tree.

**Comment by Grossley** [comment]
The following have been implemented:

* Extension Editor
* Audio Player

Is this roadmap plan still current and being maintained, or is it obsolete?

**Comment by Grossley** [comment]
If so, current issues that have been implemented should be marked as such.

**Comment by colinator27** [comment]
This is pretty obsolete now, so I'll close this.
