### ISSUE TITLE
Debug Tab not appearing

### ISSUE THREAD

**Issue by ExisantAccount** [UnderminersTeam/UndertaleModTool#1823]
### Describe the bug

I get an error message whenever I open the .sln file and the debug tab isn't there. I already have activated the debug menu on Undertale so I'm not sure if it matters if the debug tab isn't there. I'm not sure if I'm doing any of the instructions wrong to cause this. I also don't see the start button anywhere and the only green arrow I see is the Attach button arrow.

### Reproducing steps

All I did was open the .sln file and got the error message.

### Setup Details

e

**Comment by Jacky720** [comment]
This sounds like an issue with your personal development environment. Is there a particular reason you need to build the tool from source yourself? There are bleeding edge releases up to the latest accepted commit.

If you do have a particular reason you need to compile the tool, please share the error message.

**Comment by ExisantAccount** [comment]
Hi, I forgot to add the error message, so here's the picture of it.
![image](https://github.com/UnderminersTeam/UndertaleModTool/assets/175050067/78d2743d-a5bd-4d58-9928-dc2995801a92)

**Comment by Jacky720** [comment]
Do you see your Output Window anywhere, and if so, what's in it?

Again, are you positive you can't use the automatic compiled releases?

**Comment by ExisantAccount** [comment]
Yes, I do see the output window and it says:

**Comment by ExisantAccount** [comment]
I do see the output box, but the message says my real name in it.

**Comment by ExisantAccount** [comment]
Ok, I extracted the folder and it looks like it's working now.

**Comment by ExisantAccount** [comment]
Finally I got it to work, I just might've forgot to extract it.
