### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by sirenboke** [UnderminersTeam/UndertaleModTool#1841]
### Describe the bug

![屏幕截图 2024-07-22 154540](https://github.com/user-attachments/assets/edd075b1-6468-4504-95a5-0b3f1e4b77d2)
Attempting to load Dungeon Raiders TEST gives a failing to find reference error.

### Reproducing steps

Open UndertaleModTool
Drag Dungeon Raiders TEST latest version into UndertaleModTool.
Get the error

### Setup Details

UndertaleModTool v0.5.1.0 Bleeding edge
GameMaker Game ：Dungeon Raiders TEST https://erohz.itch.io/tpdr

**Comment by sonic3XE** [comment]
This is a similar VARI chunk error like in #1420, #1803 and #1819.

**Comment by colinator27** [comment]
I tested this on the `underanalyzer` branch and the game loads successfully. This should be closed by the time that branch is merged in.
