### ISSUE TITLE
Fields of Mistria game's editing with UTMT can't be saved

### ISSUE THREAD

**Issue by law4x** [UnderminersTeam/UndertaleModTool#1855]
### Describe the bug

![b94bff63964c5ab914a998e42a9f0fbf](https://github.com/user-attachments/assets/60dbb203-c4d2-4ea3-8a59-81603b037e8c)

Support  Fields Of Mistria！

### Reproducing steps

Modify anywhere, or leave it as is and save as

### Setup Details

UTMT : V0.5.1.0-(Git: 6dba40a)
Fields Of Mistria : 2024.6.0.0

**Comment by logie-github** [comment]
I'm not even able to load the data.win into the UTMT. I keep getting this error, any tips?
![image](https://github.com/user-attachments/assets/f36d1749-15b7-4385-be3b-04f6a99840ef)
![image](https://github.com/user-attachments/assets/a6bd57bf-989f-4a2f-9c90-6d9385880946)

**Comment by colinator27** [comment]
I believe I have a fix for this issue, would either of you mind testing out the builds from https://github.com/UnderminersTeam/UndertaleModTool/pull/1857#issuecomment-2276693344? Thanks.

**Comment by logie-github** [comment]
This works for me! Thanks! This also fixes the issue with importing the data.win file.
![image](https://github.com/user-attachments/assets/7a9bc7b4-59c3-48e9-abed-32402d1b72b7)

**Comment by colinator27** [comment]
Sweet, thanks for trying it out!
