### ISSUE TITLE
Texture Worker does not contain a definition for 'Cleanup" and no accessible extension method 'Cleanup' accepting a first argument of type TextureWorker.

### ISSUE THREAD

**Issue by donsoyer** [UnderminersTeam/UndertaleModTool#1882]
### Describe the bug

![obraz](https://github.com/user-attachments/assets/3617fd7e-8f07-458a-a249-a16753140692)

### Reproducing steps

Data has been loaded, all scipts work, but Resource Unpackers: ExportAllSprites and ExportAllTilests are not working. 
It happens in every game made in Gamemaker. So the problem is not in the game, but in the newest builds of UndertaleModTool.

UndertaleModTool BlEd-isSingleFile-true (newest) also UndertaleModTool_v0.6.1.0-SingleFile - on these the scripts are not working. But on the previous ones (0.6.0.0, 0.5xx, 0.4xx and so on) sripts are working very well.

How do I modify these scripts to make them work?

### Setup Details

1. UndertaleModTool BlEd-isSingleFile-true (newest) also UndertaleModTool_v0.6.1.0-SingleFile - on these the scripts are not working. But on the previous ones (0.6.0.0, 0.5xx, 0.4xx and so on) sripts are working very well. * - (on 0.6.1.0 script is working well - my mistake)
2. Win 10.
3. Every game made in Gamemaker. So the problem is not in the game, but in the newest builds of UndertaleModTool.

**Comment by colinator27** [comment]
This is known, bleeding edge texture scripts are not yet updated (will be fixed in an upcoming PR). If you want to use a stable release, use 0.6.1.0. https://github.com/UnderminersTeam/UndertaleModTool/releases/tag/0.6.1.0

**Comment by Miepee** [comment]
@donsoyer please double check that it is *actually* working on 0.6.1.0.

**Comment by donsoyer** [comment]
Yeah, 0.6.1.0 is ok. My mistake. Thanks

pt., 23 sie 2024 o 20:11 Miepee ***@***.***> napisał(a):

**Comment by Miepee** [comment]
Closing as not an issue, as this is an intended breakage on the master branch / bleeding edge builds.
