### ISSUE TITLE
Add gridless option.

### ISSUE THREAD

**Issue by NC-devC** [UnderminersTeam/UndertaleModTool#1888]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

I think would be good to have option in settings that would disable or enable grid in rooms.

**Comment by NC-devC** [comment]
Ok, its already exists. Sorry

**Comment by Miepee** [comment]
cant you just set the grid thickness to 0?

**Comment by NC-devC** [comment]
> cant you just set the grid thickness to 0?

Thx, i dont found it before
