### ISSUE TITLE
Error opening Home World Run's data.win file. 

### ISSUE THREAD

**Issue by TehFridge** [UnderminersTeam/UndertaleModTool#1907]
### Describe the bug

![image](https://github.com/user-attachments/assets/04d26366-c47d-4969-b9bc-bfca2169941e)

### Reproducing steps

1. Get Home World Run's SAGE 2024 Demo.
2. Open its data.win file with UMT
3. error

### Setup Details

1. UndertaleModTool Bleeding Edge (git: 9f4f13a)
2. Windows 11 
3. Game: https://sonicfangameshq.com/forums/showcase/home-world-run.2124/

**Comment by sonic3XE** [comment]
This is where images with header "DDS " are not implemented yet.

**Comment by luizzeroxis** [comment]
Can you try this and see if it works?

https://github.com/luizzeroxis/UndertaleModTool/actions/runs/11062600291/artifacts/1985298096

**Comment by TehFridge** [comment]
Yes it works now!
Thank you so much.

**Comment by sonic3XE** [comment]
DDS images may fit for issue number 1932.
