### ISSUE TITLE
UndertaleModTool crashes when importing sprites

### ISSUE THREAD

**Issue by Tinfox2** [UnderminersTeam/UndertaleModTool#1918]
### Describe the bug

When I try to import the exported sprites into the data.win, the tool crashes. There is a file that it has an issue with, and the tool crashes regardless of if I say yes or no.

![image](https://github.com/user-attachments/assets/81b727f6-cd8b-4601-b32a-e77ac706ee1e)
![image](https://github.com/user-attachments/assets/8d44df9e-4060-44da-80ca-b251d3d5f7bb)

### Reproducing steps

1. Open UndertaleModTool
2. Go to Scripts, Resource Repackers, and ImportGraphics
3. Run the script
Notes: This happens regardless of if the sprites are exported into subfolders or not.

### Setup Details

UndertaleModTool version: 0.6.1.0
OS: Windows 10
Game: Pizza Tower

**Comment by Jacky720** [comment]
Typically you don't want to bulk import every sprite in the game due to ImportGraphics always repacking new texture pages. You are likely encountering a memory issue from loading too many sprites at once; try moving only the sprites you actually modified into a separate folder and importing that.

**Comment by Tinfox2** [comment]
That worked! Thanks!
