### ISSUE TITLE
Failed to recognize any known image header in Nova Drift data.win

### ISSUE THREAD

**Issue by MangoTCF** [UnderminersTeam/UndertaleModTool#1944]
### Describe the bug

Trying to open data.win in the bleeding edge ubuntu CLI or the stable Windows GUI releases results in a variation of the following error: 
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> UndertaleModLib.UndertaleSerializationException: Failed to recognize any known image header
at 00B29688 while reading object UndertaleModLib.Models.UndertaleEmbeddedTexture+TexData in chunk TXTR
 ---> UndertaleModLib.UndertaleSerializationException: Failed to recognize any known image header
at 00B29688 while reading object UndertaleModLib.Models.UndertaleEmbeddedTexture+TexData
 ---> System.IO.IOException: Failed to recognize any known image header

### Reproducing steps

1. try to do anything with the Nova Drift data.win file
2. Observe the crash

### Setup Details

1. the bleeding edge ubuntu CLI(as of 06.10.2024) or the stable Windows GUI
2. Arch Linux, kver 6.11.1-arch1-1.1
3. Nova Drift v1.0

**Comment by luizzeroxis** [comment]
I don't have access to this game, could you try [this build](https://github.com/UnderminersTeam/UndertaleModTool/pull/1929#issuecomment-2379597799)? It's probably the same issue.

**Comment by sonic3XE** [comment]
If the image was GPU compressed, it would be #1932

**Comment by MangoTCF** [comment]
> I don't have access to this game, could you try [this build](https://github.com/UnderminersTeam/UndertaleModTool/pull/1929#issuecomment-2379597799)? It's probably the same issue.

That worked, thanks!
