### ISSUE TITLE
Invisible Sprites

### ISSUE THREAD

**Issue by Final-Quota** [UnderminersTeam/UndertaleModTool#1962]
### Describe the bug

I edited some sprites by making a new spite sheet and when I booted up the game, the sprites I added/changed where invisible

### Reproducing steps

1. I edited some sprites with new sprite sheets since I couldn't use the old spite sheets
2. I booted up the game using "Temp run game"
3. When I got to the part where the sprites where supposed to be they where blank
![Screenshot (232)](https://github.com/user-attachments/assets/4de2cb68-49c9-479a-b467-94274c21490a)
![Screenshot (233)](https://github.com/user-attachments/assets/df50dc9c-e759-4a2f-ad8e-2881049f06e4)

### Setup Details

1. I used UndertaleModTool v:0.6.1.0
2. I using the operating system Windows 10
3. I am moding the game Deltarune (https://store.steampowered.com/app/1671210/DELTARUNE/)

**Comment by Final-Quota** [comment]
I got a new problem but this one is fixed, I think

**Comment by Mikomoee** [comment]
I have the same problem, how did you fix it?

**Comment by Mikomoee** [comment]
> I have the same problem, how did you fix it?

nevermind, i found it
