### ISSUE TITLE
Sprites become "blurry" once imported

### ISSUE THREAD

**Issue by wulbz** [UnderminersTeam/UndertaleModTool#312]
I've been working on replacing Frisk's sprites and I've run into and issue when I import them. What I've been doing is that I remake the sprite with the same dimensions (as opposed to editing the sprite sheet itself) and then import the sprite using the UndertaleModTool. However, when loading the game up, the sprite appears "blurry." Attached is a sprite I made and how it appears in the game. I apologize if this has already been answered, but I would be really grateful if someone could help me figure this out
![spr_f_maincharad_0](https://user-images.githubusercontent.com/69997375/90842392-c57f3f00-e324-11ea-9af3-4fdd127d3ab6.png)
![NOOOO](https://user-images.githubusercontent.com/69997375/90842475-ff504580-e324-11ea-9c16-f6a2532cf731.png)

**Comment by Grossley** [comment]
Please ensure that the sprites you are importing are 96 DPI.

**Comment by wulbz** [comment]
> Please ensure that the sprites you are importing are 96 DPI.

They are

**Comment by Bluemycool320** [comment]
Are you sure that the sprites you are adding are the same size as the original sprites? If you try to replace a sprite that's 32x32 with a sprite thats 44x30 for example, UMT will stretch that file to fit the 32x32 size, which causes a blur effect similar to this one.

**Comment by Miepee** [comment]
Whats the progress on this? @wulbz are you still experiencing that issue?

**Comment by Jacky720** [comment]
Many people are able to import sprites without this issue, and the tool has changed significantly since this issue was first submitted. Closing; for further help, please create a new issue or request assistance in the Underminers Discord. (I recommend ImportGraphics.csx if that wasn't already used.)
