### ISSUE TITLE
Test project with passthrough shader compiled for vita doesn't open in UndertaleModTool

### ISSUE THREAD

**Issue by Grossley** [UnderminersTeam/UndertaleModTool#391]
This game throws an exception regarding the length of shaders. If this exception is ignored, it can resave the file, with a one byte difference. It is a very odd thing, and would like some help investigating it. 

[game.zip](https://github.com/krzys-h/UndertaleModTool/files/6160075/game.zip)

**Comment by Jacky720** [comment]
Using the UTMT debugger, it appears that the Cg_PSVita_PixelData (the last type in the shader and in the data file) is computing the expected length of the last shader, based on the end of the chunk, to be 304 while the correct length being compared by the exception is 300 (the additional four bytes are padding). An appropriate fix might be to seek out the end of the shader and verify that the additional bytes are null, or to disable the check entirely for the last section of shader data.
