### ISSUE TITLE
Code doesn't decompile

### ISSUE THREAD

**Issue by Grossley** [UnderminersTeam/UndertaleModTool#499]
This GML doesn't decompile properly:
```
var a = 0
do {
    a++;
} until a;
```

**Comment by Grossley** [comment]
Also 
```
if (keyboard_check_pressed(ord("A")))
{
    var p = pointer_null;
    if (p == pointer_invalid)
        p = self;
    else 
        p = other;
}
```

**Comment by BenjaminUrquhart** [comment]
> Also
> 
> ```
> if (keyboard_check_pressed(ord("A")))
> {
>     var p = pointer_null;
>     if (p == pointer_invalid)
>         p = self;
>     else 
>         p = other;
> }
> ```

This only happens in 2.3. Older versions are unaffected.

**Comment by Miepee** [comment]
> This GML doesn't decompile properly:
> 
> ```
> var a = 0
> do {
>     a++;
> } until a;
> ```

This is a "duplicate" of #671.

Does the second issue still happen?
