### ISSUE TITLE
object reference not set to an instance of an object error while exporting tilesets (after exporting ~10)

### ISSUE THREAD

**Issue by FlashlightET** [UnderminersTeam/UndertaleModTool#516]
![image](https://user-images.githubusercontent.com/29938499/129105491-ecdfbd56-00a7-47c7-a37a-f1c18c973063.png)

**Comment by Miepee** [comment]
For which game is this?
Since you likely don't remember the UMT version anymore, can you still reproduce it with a newer version?

**Comment by Jacky720** [comment]
Closing as stale.
