### ISSUE TITLE
i want to import fonts created from gms2 into the undertalmodtool

### ISSUE THREAD

**Issue by AnXing233** [UnderminersTeam/UndertaleModTool#527]
i want to import fonts created from gms2 into the undertalmodtool.
But I'm not very good at using underalemodtool, and the number of characters is very large,I can't modify character values one by one and import them into undertalemodtool with "ImportFontData.csx".
Also, using "TTFfonts.csx" will cause errors.
I hope to make a script to facilitate this.QAQ

**Comment by Grossley** [comment]
Resolved.
