### ISSUE TITLE
[Assets Resolution][NXTALE][1.11] Some sprites/Rooms don't get resolve

### ISSUE THREAD

**Issue by FriskTheFallenHuman** [UnderminersTeam/UndertaleModTool#533]
has the title suggest some sprites/rooms from `gml_Script_scr_draw_screen_border` don't get resolve has expected

**Comment by Jacky720** [comment]
Cannot reproduce on current bleeding edge. I assume this is because the contextual asset resolver improved or the Switch's functions and variables were added to the Undertale-specific resolutions, so, problem solved.
