### ISSUE TITLE
trying to index a variable which is not an array (line -1)

### ISSUE THREAD

**Issue by OhioInvadesUSA** [UnderminersTeam/UndertaleModTool#604]
I tried to re-add Pippins to Deltarune by editing the Placeholder Enemy's code, but this happened:
trying to index a variable which is not an array (line -1)

**Comment by Jacky720** [comment]
Does this error still occur on UndertaleModTool 0.4.0.2?

**Comment by Miepee** [comment]
This issue is missing quite a bit of info @OhioInvadesUSA

**Comment by Miepee** [comment]
No info in over 2 years. Closing as stale
