### ISSUE TITLE
Exception returned in new decompiler when reading old file (pre GMS 2.3)

### ISSUE THREAD

**Issue by ToughSun14** [UnderminersTeam/UndertaleModTool#622]
I recently got the latest version of UMT, but it seems that now under certain conditions, the decompiler actually has a problem reading certain values I have in scripts from a pre 2.3 project. Included in this issue is a zip file containing 2 folders for anyone to look at. One folder contains the files with their code intact. The other folder contains files with the errors returned from the decompiler.
[issue code.zip](https://github.com/krzys-h/UndertaleModTool/files/7316193/issue.code.zip)

**Comment by Jacky720** [comment]
@ToughSun14 Does this issue still occur?

**Comment by ToughSun14** [comment]
Well, for the gamepad scripts, no. For obj_mainchara and obj_heart, yes. I think it has to do with the multiple break statements in the code.

**Comment by Jacky720** [comment]
Those remaining issues are documented at #224. Closing as duplicate.
