### ISSUE TITLE
Add regex search to Ctrl + F in code entries

### ISSUE THREAD

**Issue by Archie-osu** [UnderminersTeam/UndertaleModTool#635]
Finding stuff in code entries through the use of regular expressions could speed things up with really long scripts. 

I know Search.csx has this option, but what it doesn't have is the option to search only one code entry.

**Comment by VladiStep** [comment]
Isn't it already there?
If you press the **▾** button in the Ctrl+F search box, it will show a list of checkboxes, one of them is "_**Use regular expressions**_".

**Comment by Archie-osu** [comment]
Yeah, it's there, just noticed it, closing.
