### ISSUE TITLE
Multi-dimension arrays have trouble recompiling

### ISSUE THREAD

**Issue by ToughSun14** [UnderminersTeam/UndertaleModTool#642]
It seems that something new toby introduced into chapter 2's code is variables with multi-dimensional arrays attached (example: arrayNameHere[array1ValueHere][array2ValueHere]) However, this seems to be a problem with the new decompiler as it can't recompile double arrays. Perhaps someone could take a look at this and introduce a fix to UMT's code for this?

**Comment by Jacky720** [comment]
This has been resolved by #706. Happy compiling!

**Comment by ToughSun14** [comment]
Well, let me say that you may have gotten 2D arrays down, but you need to also compensate for larger arrays. If I try to make a 3D array, for example, it returns an error.

**Comment by Jacky720** [comment]
Gah! I'll put it on the list. Do you have any examples, or should I build my own?

**Comment by ToughSun14** [comment]
Actually, I do have an example: in "gml_Object_obj_rouxls_simtown_Step_0", line 28, when I try to change the array reference from 2D to 3D, it returns an error. After doing some more checking, this seems to happen for any predefined array that already exists if I try to change its dimension (eg: 2D array to 3D array). My advice: change the array system back to how it was before (with the brackets defining dimensions), but update the check system so that it can detect (ex: is this a comma array or a bracket array?) and properly compile arrays.

**Comment by Jacky720** [comment]
I kind of meant an example of a 3D array being used in an existing project, so I can figure out what bytecode I'm trying to compile to. Thanks anyway.

**Comment by ToughSun14** [comment]
Oh, my bad. But in all seriousness, I think what I suggested might work. I actually ran some tests with my own GMS projects, and before the update that unified all arrays into comma arrays by the decompiler, it was actually able to tell the difference between comma and bracket arrays. All I suggest is that whatever code checks for this be improved so that it can properly compile bracket arrays.

**Comment by ToughSun14** [comment]
Actually, update: ran a test project with a 3D array, UMT returned an exception when trying to read the code block it was in.

**Comment by Jacky720** [comment]
It's been a year, and I remember doing some more tweaking and testing with this; has it been resolved?

**Comment by ToughSun14** [comment]
As far as I can tell, yes. This issue has been resolved. Arrays with a dimension greater than 2 don't throw an exception when recompiling.
