### ISSUE TITLE
Wrong decompilation - infinite loop

### ISSUE THREAD

**Issue by Archie-osu** [UnderminersTeam/UndertaleModTool#649]
``gml_Object_obj_spamton_neo_enemy_Step_2 : line 47``

The decompiler completely fails and decompiles nonsense like
```gml
var _temp_local_var_5 = 6
if (6 <= 0)
{
}
```
not to mention this code will cause an infinite loop when compiled, and will softlock the game.

![image](https://user-images.githubusercontent.com/61205459/137636422-329678e8-fb95-4e92-b840-d5aad40dd654.png)

**Comment by Miepee** [comment]
Has this been fixed with Jacky's commits?

**Comment by Jacky720** [comment]
Yes.
