### ISSUE TITLE
TGIN chunk (GM2)

### ISSUE THREAD

**Issue by LinXP** [UnderminersTeam/UndertaleModTool#70]
I'll start collecting information on TGIN chunk. 
I don't know yet what he is responsible for, but I wrote the structure of this chunk.
Screen: http://i.prntscr.com/XQQBuoxPRim05LpPL2i8LA.png

**Comment by colinator27** [comment]
Where have you found this chunk's existence?

**Comment by LinXP** [comment]
@colinator27 https://store.steampowered.com/app/356650/Deaths_Gambit/

**Comment by colinator27** [comment]
Are you sure TGIN is an actual chunk, or part of something else inside a chunk? If you haven't checked, just go through each chunk and jump to the next using its length. If TGIN doesn't show up, that means it's part of something else (maybe some other IFF-like data), but if it does then I guess we have a *really* weird chunk that I found no evidence of anywhere else.

**Comment by LinXP** [comment]
@colinator27  I think it will be better to see the size of the chunks above and below
http://i.prntscr.com/DvbFx_JZQy6qr_x3wwgflQ.png

I found a couple more games:
Rivals of Aether http://i.prntscr.com/wgBxXIM6QC2-rJcFR45lhA.png
Wandersong http://i.prntscr.com/f-Qundz1R6iSTjWOh4XThg.png

And now the most interesting: BytecodeVersion these games 17
http://i.prntscr.com/dLhnyubuS1WdQ7MGwQjgzA.png

**Comment by colinator27** [comment]
Hm, let me see if I have it in my latest compiler. I was analyzing 2.1.5, but I'll try 2.2 now.

**Comment by colinator27** [comment]
Hm, I can't seem to find anything about it (yet) in the compiler. How recently were these games built? I recall that there is a special beta branch for GMS2 somewhere...

**Comment by LinXP** [comment]
http://i.prntscr.com/HbLlKr0mQ3ydEro1R-SbGg.png
I added a link and got access to beta

GMAssetCompiler_2.2.1.277:
http://i.prntscr.com/cyiyh0jBR-KKX_FcauNw7w.png
http://i.prntscr.com/EyhvfNXnSziO89r0ZIH4Rw.png

**Comment by colinator27** [comment]
Oh wow, that's a neat trick.

**Comment by colinator27** [comment]
I'll assist in collecting some information as well then.

**Comment by colinator27** [comment]
So, I'm getting a good amount of progress. This seems to relate to the new functions they added for texture groups, and I think TGIN stands for "texture group info".

**Comment by colinator27** [comment]
Also, I just realized the implementation for this should still be a ListChunk<T>, but how EMBI does it. I'll try implementing it really quickly.

**Comment by colinator27** [comment]
Support should be added in #76.

**Comment by krzys-h** [comment]
The "1" is probably just a version number, they realized with new chunks that something like this would be useful

**Comment by colinator27** [comment]
Oh, yeah, that makes sense...
