### ISSUE TITLE
Debug mode script doesn't work for Deltarune Chapter 1

### ISSUE THREAD

**Issue by onilpa** [UnderminersTeam/UndertaleModTool#724]
it doesnt work with deltarune and that sucks pls fix that

**Comment by AllyTally** [comment]
It does work with Deltarune, we need more information. What Deltarune build? (Original or Steam?) What UTMT build? Is it up to date?

**Comment by NyakoFox** [comment]
It does work with Deltarune, we need more information. What Deltarune build? (Original or Steam?) What UTMT build? Is it up to date?

**Comment by onilpa** [comment]
i meant like you cant enable debug in deltarune steam

‫בתאריך יום ו׳, 14 בינו׳ 2022 ב-21:20 מאת ‪Nyako‬‏ <‪
***@***.***‬‏>:‬

**Comment by Dobby233Liu** [comment]
Scripts/Run community script/Ch2 Debug.csx

**Comment by onilpa** [comment]
ty your the best

‫בתאריך יום א׳, 16 בינו׳ 2022 ב-16:27 מאת ‪Liu Wenyuan‬‏ <‪
***@***.***‬‏>:‬

**Comment by onilpa** [comment]
but what about chapter 1? is there any debug mode for chapter 1/

‫בתאריך יום א׳, 16 בינו׳ 2022 ב-16:32 מאת ‪OniL Pa‬‏ ***@***.***
‬‏>:‬

**Comment by onilpa** [comment]
is there debug mode for chapter 1?

**Comment by Dobby233Liu** [comment]
in ch1&2 demo?

**Comment by Jacky720** [comment]
By any chance, is this a translated version of the game producing error messages similar to [this](https://redd.it/s4uhx8/)?

**Comment by onilpa** [comment]
No, it doesn't.

‫בתאריך יום א׳, 16 בינו׳ 2022 ב-17:07 מאת ‪Jacky720‬‏ <‪
***@***.***‬‏>:‬

**Comment by Jacky720** [comment]
Could you please send any other error messages it *is* producing?

**Comment by Jacky720** [comment]
Ch2 Debug.csx enables whatever debug functions are present in Chapter 1 of the 1&2 demo, and EnableDebug works on SURVEY_PROGRAM. Closing.
