### ISSUE TITLE
ExportAllSprites abysmally slow sometimes

### ISSUE THREAD

**Issue by Jacky720** [UnderminersTeam/UndertaleModTool#734]
Reported the script only got through 510/10466 sprites in the course of ten minutes.

Game is "Stoneshard, a turn-based RPG", and GMS2.3.

**Comment by Miepee** [comment]
@Jacky720 can you still reproduce this?

**Comment by Jacky720** [comment]
It wasn't mine, we'd have to track down the guy in the Discord.

**Comment by Miepee** [comment]
We could alternatively also buy stoneshard

**Comment by Miepee** [comment]
I'm closing this until we can reliably reproduce this.
