### ISSUE TITLE
I've tried adding a mask that would work with the sprite I'm adding. Whenever I try to import it, I get this message.

### ISSUE THREAD

**Issue by Jmotions** [UnderminersTeam/UndertaleModTool#759]
![0](https://user-images.githubusercontent.com/100193054/155094032-46275811-8886-4168-a643-5236a6fc1aa9.png)
I've tried adding a mask that would work with the sprite I'm adding. Whenever I try to import it, I get this message.
![image](https://user-images.githubusercontent.com/26528643/48678581-d5b02c00-eb4a-11e8-8ed3-fd87a9e68b3a.png)
I know it's a mistake on my part, I'm just wondering how to have it acceptable in the program.

Can you help with this (im getting the same error as someone else so I just copied there issue)

I really just want to know one if i make it a 1-bit image will it take away my color (im doing a frisk sprite edit) and if it does can I fix it

![0](https://user-images.githubusercontent.com/100193054/155094032-46275811-8886-4168-a643-5236a6fc1aa9.png)
![1](https://user-images.githubusercontent.com/100193054/155094139-cc37b234-e86a-4e10-9089-b7138af0ded5.png)
![2](https://user-images.githubusercontent.com/100193054/155094174-06812396-9a57-48d4-ac09-9e88468c9c64.png)
![3](https://user-images.githubusercontent.com/100193054/155094202-5a1d478c-bb16-4cbf-b551-2a9c7c64c0ea.png)

These are my sprites im trying to import so if there is a problem with them please tell me

**Comment by Lassebq** [comment]
1 bit image for a *mask*, not the sprite itself. A mask is a simplified shape of the sprite with white being solid and black being empty. It needs to be the same size as the sprite and importing it will not affect the visual sprite.

**Comment by Jmotions** [comment]
so do i just need to make it black and white?

**Comment by Jmotions** [comment]
and if I do how will I add color afterwards

**Comment by Jacky720** [comment]
The mask is a separate copy of the sprite. You are not editing the original, and it is impossible to add color to the mask. MS Paint should have a setting for 1-bit color.

**Comment by Jmotions** [comment]
ok so if I do add it in as black and white its just gonna use the normal color pallete?

**Comment by Jacky720** [comment]
Uh, yes, as long as you add the _mask_ in black and white without changing the _sprite_.

**Comment by Jmotions** [comment]
Ok so im looking at the sprite sheet for the entire game and I think that the mask is just collisions and if i want to change the actual sprite i find it there
![big ass image](https://user-images.githubusercontent.com/100193054/155178655-91056d56-a34d-4b3b-858d-29df437f76c6.png)

**Comment by Jmotions** [comment]
and im using ms cuz gimp is too complicated

**Comment by Jacky720** [comment]
Use the ImportGraphics/ExportAllSprites scripts in the Scripts button at the top of the mod tool menu (Repackers/Unpackers). It'll also create its own masks to match the imported sprite.

**Comment by Jmotions** [comment]
oh im just gonna copy the sprite sheet to another data.win

**Comment by Jmotions** [comment]
and creating new masks wont be necessary since I'm just making a recolored version of frisk. and I have to use a newer version because the one I have uses bytecode 14

**Comment by Jmotions** [comment]
thankyou for the help though

**Comment by Jacky720** [comment]
...do the import/export scripts not work on bytecode 14 games?

**Comment by Jmotions** [comment]
i can check

**Comment by Jmotions** [comment]
no it dosent work

**Comment by Jacky720** [comment]
The import folder may need to be named "Sprites" depending on the mod tool version.

**Comment by Jacky720** [comment]
ImportGraphics confirmed to work on Undertale v1.00. Closing for staleness.
