### ISSUE TITLE
Sprite sheet weird thing

### ISSUE THREAD

**Issue by Bunjee10** [UnderminersTeam/UndertaleModTool#787]
whenever i open the steam deltarune demo and access the spirtes, they are all messed up. 
![image](https://user-images.githubusercontent.com/101524040/158075046-22be6e3b-4533-48cc-a8a6-3a34101330fc.png)
(if it wasnt obvious, the image should be the deltarune logo, but it is a part of a wall in chapter one)

**Comment by vevakan783** [comment]
does this happen when you close and reopen it? if it does then i cant help but if its just sometimes then close it and reopen it i guess

**Comment by Miepee** [comment]
@Bunjee10 did you try this with the cutting edge builds?
https://github.com/krzys-h/UndertaleModTool/actions/workflows/publish_gui.yml

**Comment by Jacky720** [comment]
Cannot reproduce currently and over a year stale. Closing.
