### ISSUE TITLE
New value in FONT (bytecode 17)

### ISSUE THREAD

**Issue by LinXP** [UnderminersTeam/UndertaleModTool#79]
https://github.com/krzys-h/UndertaleModTool/blob/5b036f3fba8c265fc8c2ef62283f4a23e1506153/UndertaleModLib/Models/UndertaleFont.cs#L36-L37
I assume that there is a new value coming after ScaleY
checked on several games with bytecode 17
2.2.1.277 http://i.prntscr.com/hJ7gFnMzTQ_tgVFx4El9TA.png
http://i.prntscr.com/ZBj_lCi8QASDldezTbWWhA.png

**Comment by colinator27** [comment]
I already discovered this: I'm going to add a commit to my pull request fixing it.
