### ISSUE TITLE
GML Compiler causing Functions to sometimes compile incorrectly leading to them not be called.

### ISSUE THREAD

**Issue by Miepee** [UnderminersTeam/UndertaleModTool#877]
Using a mod of `deltranslate` (see [here](https://drive.google.com/file/d/1vDriknfmVhZmmh3ZZ_LuXMxvKEUmBrBt/view)` some functions compile incorrectly when using the (de)compiler. Using the (dis)assembler works without issues.
Functions that *sometimes* cause these issues are: `button1_p, button2_p, up_p, down_p, left_p, right_p, stringsetloc, ossafe_file(each of them), snd_play, instance_create and sound_free_al`. Might be more and only sometimes.
Replication steps:
- Open the data.win in UTMT
- Open `gml_Object_obj_CHAPTER_SELECT_Draw_0`
- look at the disassembly tab, scroll down a little and notice how the functions are correct
![image](https://user-images.githubusercontent.com/38186597/166118249-c73913ac-ef12-4504-802b-15ab7014460b.png)
- Go to the Decompiler tab, and do a minute change like changing `if (!audio_group_is_loaded(1))` to `if (!audio_group_is_loaded(0))`
- Go to the disassembly tab, scroll down a little and notice how the functions are wrong:
![image](https://user-images.githubusercontent.com/38186597/166118268-eaca1e2b-e456-4c4a-801a-69cb16fb150e.png)

The game will now not call these broken functions anymore:

Something further: while in the above example it's possible to see `stringsetloc` breaking, going to `gml_Obejct_obj_tensionbar_Draw_0`  and performing the same operations causes the functions to *not* break.

**Comment by Jacky720** [comment]
Disassembly looks fine following reproduction steps on current bleeding edge. @Miepee please close unless you think further testing is needed.

**Comment by Miepee** [comment]
I was opening this issue by proxy. If you say its not reproducable anymore, i believe you.
