### ISSUE TITLE
UTMT dealing with local vars weirdly

### ISSUE THREAD

**Issue by Miepee** [UnderminersTeam/UndertaleModTool#879]
Using Deltarune chapter1&2 version 1.07 (windows, itch.io, untested with other games) it's possible to get the game into a state where it will crash due to not finding built-in GameMaker functions.
Steps to replicate:
- Open the data.win in UTMT
- Open any script and add *a lot* of vars to it. 
```
var a, b, c, d, e, f, g, h, as, bg, ag, ft, gr, gy, hy, ku, bs, cd, bh, hu, bt, adft, apusdf, asdyuf, afsoibyg, asfiub, asdnyuf, bohi, asfghy, asfvy, asdfjtgo, afbiunrqf, afsbgujapf;
TYPE = 3;
var asdgtybiharf = 0
global.aasfmbu = 0
global.asfogimbputa = 0
global.ntioauebniousnb = 0
global.ejiugrnOIRUABNF = 0
global.TAEOUNUIAQGNR = 0
global.AKSFUBNGBKNLA = 0
global.afkubnli = 0
global.asfabunuilaegb = 0
global.asfogioiunearipugnb = 0
global.asfgpiuaenptbui = 0
global.asopfbnp = 0
global.asfoipgjb = 0
global.asfopbin = 0
global.asf = 0
```
- Try to run the game.

**Comment by Romualdo666** [comment]
yeah, this happened to me too. What I did to finally open the game, is deleting some of the last vars in the variables section of Undertale Mod tool.

**Comment by Miepee** [comment]
Also for DR1&2?

**Comment by Romualdo666** [comment]
Yeah

**Comment by Jacky720** [comment]
Can't reproduce with sample code and Deltarune 1.15 (I don't have 1.07 on hand). This seems like an issue that would have occurred with the variable count and been fixed since, probably good to close?

**Comment by Miepee** [comment]
TBH i cant remember whether the sample code was there to be reproducable or just as an example. Can you test with like 10x the amount of vars?

**Comment by Romualdo666** [comment]
i think this got fixed long time ago. at least for deltarune. i remember modding deltarune was a pain in the ass by then

**Comment by Miepee** [comment]
Havent heard anyone complain about this, so probably good to close
