### ISSUE TITLE
Several DND codes decompile incorrectly in the game "Dreamland"

### ISSUE THREAD

**Issue by Grossley** [UnderminersTeam/UndertaleModTool#941]
### Describe the bug

``gml_Object_kirbyflashing_Step_0.asm`` decompiles incorrectly in UndertaleModTool.

### Reproducing steps

N/A

### Setup Details

N/A

**Comment by Miepee** [comment]
Can you link the game please?

**Comment by Archie-osu** [comment]
One I found on itch.io (free) is [this one](https://leonardlc.itch.io/dreamland).

**Comment by Miepee** [comment]
Grossley's game is some Kirby fangame. The one you linked is something else, there are no references of Kirby in there.

**Comment by Jacky720** [comment]
I found three GameMaker fan games named after Kirby's Dream Land and none of them contain any assets called `kirbyflashing`. Gonna have to close as stale/can't reproduce.
