### ISSUE TITLE
UndertaleModTool should be moved to an Organization

### ISSUE THREAD

**Issue by Miepee** [UnderminersTeam/UndertaleModTool#958]
### Which component should be improved?

Other

### Describe your feature suggestion in more detail

UndertaleModTool should be moved to an Organization in order to moderate the repo easier, among other things.

**Comment by Archie-osu** [comment]
Vouch for this.
I think @krzys-h is the only one with permissions though.

**Comment by Miepee** [comment]
From the "vote" in the server:
![image](https://user-images.githubusercontent.com/38186597/173194063-673c0b6d-7b1f-4f47-baf7-8834303b2f23.png)
Grossley, and OceanBagel also agreed later IIRC

**Comment by Grossley** [comment]
I agree with this course of action. It's also kind of difficult to do everything the contributors want me to do with my current permissions and I would like greater permissions. I think that moving it to an organization could help with that.

**Comment by Miepee** [comment]
This was fixed :tada:
